/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas.Morfologia;

import Telas.Tela_Principal_;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.awt.Point;
import Processamento.Morfologia;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Eloy
 */
public class ElementoEstruturante extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ElementoEstruturante.class.getName());
    private Tela_Principal_ telaPrincipal;
    private ArrayList<Point> ElemEst;
    private BufferedImage novaImagem, imagem_original;
    private int seletor;

    /**
     * Creates new form ElementoEstruturante
     */
    public ElementoEstruturante(Tela_Principal_ telaPrincipal, int operacao){
        this.telaPrincipal = telaPrincipal;
        this.ElemEst = new ArrayList<>();
        this.seletor = operacao;
        this.novaImagem = new BufferedImage(telaPrincipal.getSelectedImg().getWidth(), telaPrincipal.getSelectedImg().getHeight(), 2);
        this.imagem_original = telaPrincipal.getSelectedImg();

        initComponents();
        buttonGroup1.add(eeCruz);
        buttonGroup1.add(eeBarraHor);
        buttonGroup1.add(eeBarraVer);
        buttonGroup1.add(eeQuadrado);
        buttonGroup1.add(eeRhombus);
//        buttonGroup1.setSelected(eeCruz, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        eeCruz = new javax.swing.JRadioButton();
        eeBarraHor = new javax.swing.JRadioButton();
        eeBarraVer = new javax.swing.JRadioButton();
        eeQuadrado = new javax.swing.JRadioButton();
        eeRhombus = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Iteracoes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecione o elemento estruturante");

        eeCruz.setText("Cruz");
        eeCruz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeCruzActionPerformed(evt);
            }
        });

        eeBarraHor.setText("Barra horizontal");
        eeBarraHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeBarraHorActionPerformed(evt);
            }
        });

        eeBarraVer.setText("Barra vertical");
        eeBarraVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeBarraVerActionPerformed(evt);
            }
        });

        eeQuadrado.setSelected(true);
        eeQuadrado.setText("Quadrado");
        eeQuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeQuadradoActionPerformed(evt);
            }
        });

        eeRhombus.setText("Rhombus");
        eeRhombus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeRhombusActionPerformed(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Iteracoes.setText("10");
        Iteracoes.setToolTipText("insira números inteiros maiores do que zero");
        Iteracoes.setMinimumSize(new java.awt.Dimension(50, 22));
        Iteracoes.setName(""); // NOI18N
        Iteracoes.setPreferredSize(new java.awt.Dimension(50, 22));

        jLabel1.setText("Iterações");

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Morfologia/elementos estruturantes.png"))); // NOI18N
        imagem.setMinimumSize(new java.awt.Dimension(50, 16));
        imagem.setPreferredSize(new java.awt.Dimension(50, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eeCruz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Iteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eeBarraHor)
                                    .addComponent(eeBarraVer)
                                    .addComponent(eeQuadrado)
                                    .addComponent(eeRhombus))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 91, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Iteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(eeCruz))
                        .addGap(26, 26, 26)
                        .addComponent(eeBarraHor)
                        .addGap(26, 26, 26)
                        .addComponent(eeBarraVer)
                        .addGap(26, 26, 26)
                        .addComponent(eeQuadrado)
                        .addGap(26, 26, 26)
                        .addComponent(eeRhombus))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
        );

        Iteracoes.getAccessibleContext().setAccessibleDescription("\"insira números inteiros maiores do que zero\"");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eeBarraHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeBarraHorActionPerformed
        // TODO add your handling code here:
//        this.seletor =2;
    }//GEN-LAST:event_eeBarraHorActionPerformed

    private void eeRhombusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeRhombusActionPerformed
        // TODO add your handling code here:
//        this.seletor =5;
    }//GEN-LAST:event_eeRhombusActionPerformed

    private void eeCruzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeCruzActionPerformed
        // TODO add your handling code here:
//        this.seletor =1;

    }//GEN-LAST:event_eeCruzActionPerformed

    private void eeBarraVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeBarraVerActionPerformed
        // TODO add your handling code here:
//        this.seletor =3;
    }//GEN-LAST:event_eeBarraVerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tipoEE = "";
        if (eeCruz.isSelected()) {
            this.ElemEst.add(new Point(0, -1));
            this.ElemEst.add(new Point(-1, 0));
            this.ElemEst.add(new Point(0, 0));
            this.ElemEst.add(new Point(0, 1));
            this.ElemEst.add(new Point(1, 0));
            tipoEE = "Cruz";
        }

        if (eeBarraHor.isSelected()) {
            this.ElemEst.add(new Point(-1, 0));
            this.ElemEst.add(new Point(0, 0));
            this.ElemEst.add(new Point(1, 0));
            tipoEE = "BarraHorizontal";
        }

        if (eeBarraVer.isSelected()) {
            this.ElemEst.add(new Point(0, -1));
            this.ElemEst.add(new Point(0, 0));
            this.ElemEst.add(new Point(0, 1));
            tipoEE = "BarraVertical";
        }

        if (eeQuadrado.isSelected()) {
            this.ElemEst.add(new Point(-1, -1));
            this.ElemEst.add(new Point(0, -1));
            this.ElemEst.add(new Point(1, -1));
            this.ElemEst.add(new Point(-1, 0));
            this.ElemEst.add(new Point(0, 0));
            this.ElemEst.add(new Point(0, 1));
            this.ElemEst.add(new Point(-1, 1));
            this.ElemEst.add(new Point(1, 0));
            this.ElemEst.add(new Point(1, 1));
            tipoEE = "Quadrado";
        }
        if (eeRhombus.isSelected()) {
            this.ElemEst.add(new Point(-1, -2));
            this.ElemEst.add(new Point(0, -2));
            this.ElemEst.add(new Point(-1, 2));
            this.ElemEst.add(new Point(-2, -1));
            this.ElemEst.add(new Point(-1, -1));
            this.ElemEst.add(new Point(0, -1));
            this.ElemEst.add(new Point(1, -1));
            this.ElemEst.add(new Point(2, -1));
            this.ElemEst.add(new Point(-2, 0));
            this.ElemEst.add(new Point(-1, 0));
            this.ElemEst.add(new Point(0, 0));
            this.ElemEst.add(new Point(1, 0));
            this.ElemEst.add(new Point(2, 0));
            this.ElemEst.add(new Point(-2, 1));
            this.ElemEst.add(new Point(-1, 1));
            this.ElemEst.add(new Point(0, 1));
            this.ElemEst.add(new Point(1, 1));
            this.ElemEst.add(new Point(2, 1));
            this.ElemEst.add(new Point(-1, 2));
            this.ElemEst.add(new Point(0, 2));
            this.ElemEst.add(new Point(1, 2));
            tipoEE = "Rhombus";
        }
        int repeticoes = Integer.parseInt(Iteracoes.getText());
        
        String sufixo = "";
        String nomeBase = telaPrincipal.getSelectedImgName();
        if (seletor == 1) {
            this.novaImagem = Morfologia.erosaoNivelDeCinza(this.imagem_original, ElemEst, repeticoes);
            sufixo = "_erosao_" + tipoEE + "_" + repeticoes + "X";
        }

        if (seletor == 2) {
            this.novaImagem = Morfologia.dilatacaoNivelDeCinza(this.imagem_original, ElemEst, repeticoes);
            sufixo = "_dilatacao_" + tipoEE + "_" + repeticoes + "X";
        }

        if (seletor == 3) {
            this.novaImagem = Morfologia.aberturaNivelDeCinza(this.imagem_original, ElemEst, repeticoes);
            sufixo = "_abertura_" + tipoEE + "_" + repeticoes + "X";
        }

        if (seletor == 4) {
            this.novaImagem = Morfologia.fechamentoNivelDeCinza(this.imagem_original, ElemEst, repeticoes);
            sufixo = "_fechamento_" + tipoEE + "_" + repeticoes + "X";
        }

        if (seletor == 5) {
            this.novaImagem = Morfologia.tophatAbertura(this.imagem_original, ElemEst, repeticoes);
            sufixo = "_tophatAbertura_" + tipoEE + "_" + repeticoes + "X";
        }

        if (seletor == 6) {
            this.novaImagem = Morfologia.tophatFechamento(this.imagem_original, ElemEst, repeticoes);
            sufixo = "_tophatfechamento_" + tipoEE + "_" + repeticoes + "X";
        }

        telaPrincipal.openInternalImg(this.novaImagem, nomeBase, sufixo);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void eeQuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeQuadradoActionPerformed
        // TODO add your handling code here:
//        this.seletor =4;

    }//GEN-LAST:event_eeQuadradoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new ElementoEstruturante().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Iteracoes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton eeBarraHor;
    private javax.swing.JRadioButton eeBarraVer;
    private javax.swing.JRadioButton eeCruz;
    private javax.swing.JRadioButton eeQuadrado;
    private javax.swing.JRadioButton eeRhombus;
    private javax.swing.JLabel imagem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
