package Telas.Morfologia;

import Processamento.Morfologia;
import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import Telas.util.Tela_Carregamento_;
import java.awt.Point;
import java.util.ArrayList;

/**
 * @author João Victor do Rozário Recla - 2022/2
 */
public class Tela_Aplicacao_Lote_Morfologia extends javax.swing.JFrame {

    // Tipos de aplicacao.
    public boolean Detectar_RI = false;
    public boolean Detectar_BI = false;
    public boolean Aplicar_segmentacao = false;

    // Nome do metodo a ser aplicado.
//    public String Metodo_nome = "_Metodo_";
    public int Segmentacao_tipo = 0;

    // Atributos.
    private int Qnt_imagens;
    private boolean Finalizado = false;
    private int Qnt_imgs_processadas = 0;
    private File Pasta_origem, Pasta_destino;
    public File Caminho = new File("/home/");
    private boolean Escolheu_origem = false, Escolheu_destino = false;
    private int Qnt_iteracoes;

    /**
     * Creates new form TelaPostPasta
     */
    public Tela_Aplicacao_Lote_Morfologia() {
//        this.ElemEst = new ArrayList<>();
        initComponents();
        buttonGroup1.add(erosao);
        buttonGroup1.add(dilatacao);
        buttonGroup1.add(abertura);
        buttonGroup1.add(fechamento);
        buttonGroup1.add(tophat_abertura);
        buttonGroup1.add(tophat_fechamento);
        buttonGroup2.add(eeCruz);
        buttonGroup2.add(eeBarraHorizontal);
        buttonGroup2.add(eeBarraVertical);
        buttonGroup2.add(eeQuadrado);
        buttonGroup2.add(eeRhombus);
        Mensagem_Aviso_.setVisible(false);
//        this.Qnt_iteracoes = Integer.parseInt(iteracoes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Campo_Pasta_Origem_ = new javax.swing.JTextField();
        Selecionar_Pasta_Origem_ = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Campo_Pasta_Destino_ = new javax.swing.JTextField();
        Selecionar_Pasta_Destino_ = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Opcao_PNG_ = new javax.swing.JRadioButton();
        Opcao_JPG_ = new javax.swing.JRadioButton();
        Opcao_BMP_ = new javax.swing.JRadioButton();
        Cancelar_ = new javax.swing.JButton();
        Aplicar_ = new javax.swing.JButton();
        erosao = new javax.swing.JRadioButton();
        dilatacao = new javax.swing.JRadioButton();
        abertura = new javax.swing.JRadioButton();
        fechamento = new javax.swing.JRadioButton();
        tophat_abertura = new javax.swing.JRadioButton();
        tophat_fechamento = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        iteracoes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        eeCruz = new javax.swing.JRadioButton();
        eeBarraHorizontal = new javax.swing.JRadioButton();
        eeQuadrado = new javax.swing.JRadioButton();
        eeBarraVertical = new javax.swing.JRadioButton();
        eeRhombus = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        Mensagem_Aviso_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplicação em Lote");
        setFocusCycleRoot(false);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplicação em Lote");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Selecione uma pasta com arquivos de imagem:");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        Campo_Pasta_Origem_.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Campo_Pasta_Origem_.setText("Selecione uma pasta de origem...");
        Campo_Pasta_Origem_.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Selecionar_Pasta_Origem_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Selecionar_Pasta_Origem_.setText("Selecionar...");
        Selecionar_Pasta_Origem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selecionar_Pasta_Origem_ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Selecione uma pasta para salvar as imagens processadas:");

        Campo_Pasta_Destino_.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Campo_Pasta_Destino_.setText("Selecione uma pasta de destino...");
        Campo_Pasta_Destino_.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Selecionar_Pasta_Destino_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Selecionar_Pasta_Destino_.setText("Selecionar...");
        Selecionar_Pasta_Destino_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selecionar_Pasta_Destino_ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Selecione a(s) extensão(ões) das imagens que devem ser  processadas:");

        Opcao_PNG_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Opcao_PNG_.setSelected(true);
        Opcao_PNG_.setText("PNG");

        Opcao_JPG_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Opcao_JPG_.setText("JPEG/JPG");

        Opcao_BMP_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Opcao_BMP_.setText("BMP");

        Cancelar_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Cancelar_.setText("Cancelar");
        Cancelar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_ActionPerformed(evt);
            }
        });

        Aplicar_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_.setText("Aplicar");
        Aplicar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_ActionPerformed(evt);
            }
        });

        erosao.setSelected(true);
        erosao.setText("Erosão");
        erosao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erosaoActionPerformed(evt);
            }
        });

        dilatacao.setText("Dilatação");

        abertura.setText("Abertura");

        fechamento.setText("Fechamento");

        tophat_abertura.setText("Tophat Abertura");

        tophat_fechamento.setText("Tophat Fechamento");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Operação morfológica:");

        iteracoes.setText("1");
        iteracoes.setMinimumSize(new java.awt.Dimension(65, 22));
        iteracoes.setPreferredSize(new java.awt.Dimension(65, 22));
        iteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iteracoesActionPerformed(evt);
            }
        });

        jLabel6.setText("Iterações:");

        eeCruz.setSelected(true);
        eeCruz.setText("Cruz");
        eeCruz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeCruzActionPerformed(evt);
            }
        });

        eeBarraHorizontal.setText("Barra horizontal");

        eeQuadrado.setText("Quadrado");

        eeBarraVertical.setText("Barra vertical");

        eeRhombus.setText("Rhombus");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Elemento estruturante:");

        Mensagem_Aviso_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mensagem_Aviso_.setForeground(new java.awt.Color(255, 0, 51));
        Mensagem_Aviso_.setText("[Mensagem de aviso]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Campo_Pasta_Origem_)
                                .addComponent(Campo_Pasta_Destino_, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Selecionar_Pasta_Destino_, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Selecionar_Pasta_Origem_, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Cancelar_, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Aplicar_, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Opcao_PNG_)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Opcao_JPG_)
                            .addGap(18, 18, 18)
                            .addComponent(Opcao_BMP_)
                            .addGap(94, 94, 94)
                            .addComponent(Mensagem_Aviso_))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tophat_fechamento)
                        .addComponent(dilatacao)
                        .addComponent(fechamento)
                        .addComponent(abertura)
                        .addComponent(tophat_abertura)
                        .addComponent(erosao))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(eeRhombus)
                                .addComponent(eeQuadrado)
                                .addComponent(eeBarraVertical)
                                .addComponent(eeBarraHorizontal)
                                .addComponent(eeCruz))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(erosao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eeCruz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eeBarraHorizontal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eeBarraVertical)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eeQuadrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eeRhombus)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dilatacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abertura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tophat_abertura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tophat_fechamento)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Campo_Pasta_Origem_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Selecionar_Pasta_Origem_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Campo_Pasta_Destino_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Selecionar_Pasta_Destino_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opcao_JPG_)
                    .addComponent(Opcao_BMP_)
                    .addComponent(Opcao_PNG_)
                    .addComponent(Mensagem_Aviso_))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar_)
                    .addComponent(Aplicar_))
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*  Metodo para selecionar uma pasta com arquivos de imagem.    */
    private void Selecionar_Pasta_Origem_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selecionar_Pasta_Origem_ActionPerformed

        try {

            // Configura e abre uma janela de dialogo.
            JFileChooser Fs = new JFileChooser(Caminho);
            Fs.setDialogTitle("Selecione uma pasta com arquivos de imagem...");
            Fs.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            Fs.setAcceptAllFileFilterUsed(false);
            int Retorno = Fs.showOpenDialog(null);

            // Seleciona a pasta.
            if (Retorno == JFileChooser.APPROVE_OPTION) {

                Campo_Pasta_Origem_.setText(Fs.getSelectedFile().getPath());
                Pasta_origem = Fs.getSelectedFile();
                Caminho = Fs.getCurrentDirectory();
                Escolheu_origem = true;
            }
        } catch (NullPointerException ex) {
            Logger.getLogger(Tela_Aplicacao_Lote_Morfologia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Selecionar_Pasta_Origem_ActionPerformed

    /*  Metodo para aplicar algoritmos em um lote de imagens.   */
    private void Aplicar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_ActionPerformed

        if (Escolheu_origem && Escolheu_destino) {

            Finalizado = false;
            Qnt_imagens = 0;
            Qnt_imgs_processadas = 0;
            Mensagem_Aviso_.setVisible(false);

            // Calcula a quantidade de arquivos de imagem na pasta de origem.
            for (File Arquivos : Pasta_origem.listFiles()) {

                if ((Opcao_PNG_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".png"))
                        || (Opcao_JPG_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".jpg"))
                        || (Opcao_JPG_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".jpeg"))
                        || (Opcao_BMP_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".bmp"))) {
                    Qnt_imagens++;
                }
            }

            // Cria uma Thread.
            Thread T1 = new Thread() {

                @Override

                public void run() {
                    ArrayList<Point> ElemEst = new ArrayList<>();
                    for (File Arquivos : Pasta_origem.listFiles()) {

                        // Identifica os arquivos de imagem, com a extensao selecionada, dentro da pasta.
                        if ((Opcao_PNG_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".png"))
                                || (Opcao_JPG_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".jpg"))
                                || (Opcao_JPG_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".jpeg"))
                                || (Opcao_BMP_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".bmp"))) {

                            try {

                                // Pega uma imagem.
                                BufferedImage Img_original = ImageIO.read(Arquivos);
                                BufferedImage Img_Processada = new BufferedImage(Img_original.getWidth(), Img_original.getHeight(), 2);

                                // Aplica algum algoritmo.
//                                if (Detectar_RI) {
//                                    Img_Processada = Processamento_Imagem_.RI_(Img_original);
//                                } else if (Detectar_BI) {
//                                    Img_Processada = Processamento_Imagem_.BI_(Img_original);
//                                } else if (Aplicar_segmentacao) {
//                                    Img_Processada = Processamento_Imagem_.Segment_(Img_original, Segmentacao_tipo);
//                                }
                                String tipoEE = "";
                                if (eeCruz.isSelected()) {
                                    ElemEst.add(new Point(0, -1));
                                    ElemEst.add(new Point(0, 1));
                                    ElemEst.add(new Point(-1, 0));
                                    ElemEst.add(new Point(0, 0));
                                    ElemEst.add(new Point(1, 0));
                                    tipoEE = "Cruz";
                                }

                                if (eeBarraHorizontal.isSelected()) {
                                    ElemEst.add(new Point(-1, 0));
                                    ElemEst.add(new Point(0, 0));
                                    ElemEst.add(new Point(1, 0));
                                    tipoEE = "BarraHorizontal";
                                }

                                if (eeBarraVertical.isSelected()) {
                                    ElemEst.add(new Point(0, -1));
                                    ElemEst.add(new Point(0, 1));
                                    ElemEst.add(new Point(0, 0));
                                    tipoEE = "BarraVertical";
                                }

                                if (eeQuadrado.isSelected()) {
                                    ElemEst.add(new Point(0, -1));
                                    ElemEst.add(new Point(0, 1));
                                    ElemEst.add(new Point(0, 0));
                                    ElemEst.add(new Point(-1, 1));
                                    ElemEst.add(new Point(-1, -1));
                                    ElemEst.add(new Point(-1, 0));
                                    ElemEst.add(new Point(1, -1));
                                    ElemEst.add(new Point(1, 0));
                                    ElemEst.add(new Point(1, 1));
                                    tipoEE = "Quadrado";
                                }
                                if (eeRhombus.isSelected()) {
                                    ElemEst.add(new Point(0, -1));
                                    ElemEst.add(new Point(0, 1));
                                    ElemEst.add(new Point(0, 0));
                                    ElemEst.add(new Point(-1, 1));
                                    ElemEst.add(new Point(-1, -1));
                                    ElemEst.add(new Point(-1, 0));
                                    ElemEst.add(new Point(1, -1));
                                    ElemEst.add(new Point(1, 0));
                                    ElemEst.add(new Point(1, 1));
                                    ElemEst.add(new Point(2, -1));
                                    ElemEst.add(new Point(2, 0));
                                    ElemEst.add(new Point(2, 1));
                                    ElemEst.add(new Point(-2, -1));
                                    ElemEst.add(new Point(-2, 0));
                                    ElemEst.add(new Point(-2, 1));
                                    ElemEst.add(new Point(1, -2));
                                    ElemEst.add(new Point(0, -2));
                                    ElemEst.add(new Point(-1, -2));
                                    ElemEst.add(new Point(1, 2));
                                    ElemEst.add(new Point(0, 2));
                                    ElemEst.add(new Point(-1, 2));
                                    tipoEE = "Rhombus";
                                }
                                int repeticoes = Integer.parseInt(iteracoes.getText());

                                String sufixo = "";
                                
                                if (erosao.isSelected()) {
                                    Img_Processada = Morfologia.erosaoNivelDeCinza(Img_original, ElemEst, repeticoes);
                                    sufixo = "_erosao_" + tipoEE + "_" + repeticoes + "X";
                                }

                                if (dilatacao.isSelected()) {
                                    Img_Processada = Morfologia.dilatacaoNivelDeCinza(Img_original, ElemEst, repeticoes);
                                    sufixo = "_dilatacao_" + tipoEE + "_" + repeticoes + "X";
                                }

                                if (abertura.isSelected()) {
                                    Img_Processada = Morfologia.aberturaNivelDeCinza(Img_original, ElemEst, repeticoes);
                                    sufixo = "_abertura_" + tipoEE + "_" + repeticoes + "X";
                                }

                                if (fechamento.isSelected()) {
                                    Img_Processada = Morfologia.fechamentoNivelDeCinza(Img_original, ElemEst, repeticoes);
                                    sufixo = "_fechamento_" + tipoEE + "_" + repeticoes + "X";
                                }

                                if (tophat_abertura.isSelected()) {
                                    Img_Processada = Morfologia.tophatAbertura(Img_original, ElemEst, repeticoes);
                                    sufixo = "_tophatAbertura_" + tipoEE + "_" + repeticoes + "X";
                                }

                                if (tophat_fechamento.isSelected()) {
                                    Img_Processada = Morfologia.tophatFechamento(Img_original, ElemEst, repeticoes);
                                    sufixo = "_tophatfechamento_" + tipoEE + "_" + repeticoes + "X";
                                }

                                // Salva a imagem processada.
                                File Fo = new File(Pasta_destino.getPath() + "/" + Arquivos.getName().substring(0, Arquivos.getName().length() - 4) + sufixo + ".png");
                                ImageIO.write(Img_Processada, "png", Fo);
                                Qnt_imgs_processadas++;

                            } catch (IOException ex) {
                                Logger.getLogger(Tela_Aplicacao_Lote_Morfologia.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }

                    Finalizado = true;
                }
            };

            T1.start();   // Inicia a Thread.

            // Cria uma Thread.
            Thread T2 = new Thread() {

                @Override

                public void run() {

                    // Exibe e executa uma janela de carregamento.
                    Tela_Carregamento_ Tc = new Tela_Carregamento_();
                    Tc.setVisible(true);
                    while (!Finalizado) {

                        Tc.Atualizar_Progresso_(Qnt_imgs_processadas, Qnt_imagens);
                    }
                    Tc.dispose();

                    if (Qnt_imgs_processadas > 0) {

                        // Exibe uma mensagem confirmando o fim da aplicacao do algoritmo.
                        JOptionPane.showMessageDialog(rootPane, Qnt_imgs_processadas + " imagens foram processadas com sucesso!", "Aplicação realizada!", JOptionPane.INFORMATION_MESSAGE);
                        Desktop desktop = Desktop.getDesktop();

                        try {
                            desktop.open(Pasta_destino);    // Abre a pasta de destino.
                        } catch (IOException ex) {
                            Logger.getLogger(Tela_Aplicacao_Lote_Morfologia.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {

                        Mensagem_Aviso_.setText("Não foram encontradas imagens, com as extensões especificadas, na pasta de origem!");
                        Mensagem_Aviso_.setVisible(true);
                    }
                }
            };

            T2.start();   // Inicia a Thread.

        } else if (!Escolheu_origem) {

            Mensagem_Aviso_.setText("A pasta de origem não foi especificada!");
            Mensagem_Aviso_.setVisible(true);
        } else if (!Escolheu_destino) {

            Mensagem_Aviso_.setText("A pasta de destino não foi especificada!");
            Mensagem_Aviso_.setVisible(true);
        }
    }//GEN-LAST:event_Aplicar_ActionPerformed

    /*  Metodo para cancelar a aplicacao de algum
        algoritmo em um lote de imagens.    */
    private void Cancelar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_ActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cancelar_ActionPerformed

    /*  Metodo para selecionar uma pasta de destino para as imagens processadas.    */
    private void Selecionar_Pasta_Destino_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selecionar_Pasta_Destino_ActionPerformed

        try {

            // Configura e abre uma janela de dialogo.
            JFileChooser Fs = new JFileChooser(Caminho);
            Fs.setDialogTitle("Selecione uma pasta para as imagens processadas...");
            Fs.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            Fs.setAcceptAllFileFilterUsed(false);
            int Retorno = Fs.showOpenDialog(null);

            // Seleciona a pasta.
            if (Retorno == JFileChooser.APPROVE_OPTION) {

                Campo_Pasta_Destino_.setText(Fs.getSelectedFile().getPath());
                Pasta_destino = Fs.getSelectedFile();
                Caminho = Fs.getCurrentDirectory();
                Escolheu_destino = true;
            }
        } catch (NullPointerException ex) {
            Logger.getLogger(Tela_Aplicacao_Lote_Morfologia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Selecionar_Pasta_Destino_ActionPerformed

    private void erosaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erosaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_erosaoActionPerformed

    private void iteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iteracoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iteracoesActionPerformed

    private void eeCruzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeCruzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eeCruzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Aplicacao_Lote_Morfologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Aplicacao_Lote_Morfologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Aplicacao_Lote_Morfologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Aplicacao_Lote_Morfologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Aplicacao_Lote_Morfologia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aplicar_;
    private javax.swing.JTextField Campo_Pasta_Destino_;
    private javax.swing.JTextField Campo_Pasta_Origem_;
    private javax.swing.JButton Cancelar_;
    private javax.swing.JLabel Mensagem_Aviso_;
    private javax.swing.JRadioButton Opcao_BMP_;
    private javax.swing.JRadioButton Opcao_JPG_;
    private javax.swing.JRadioButton Opcao_PNG_;
    private javax.swing.JButton Selecionar_Pasta_Destino_;
    private javax.swing.JButton Selecionar_Pasta_Origem_;
    private javax.swing.JRadioButton abertura;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton dilatacao;
    private javax.swing.JRadioButton eeBarraHorizontal;
    private javax.swing.JRadioButton eeBarraVertical;
    private javax.swing.JRadioButton eeCruz;
    private javax.swing.JRadioButton eeQuadrado;
    private javax.swing.JRadioButton eeRhombus;
    private javax.swing.JRadioButton erosao;
    private javax.swing.JRadioButton fechamento;
    private javax.swing.JTextField iteracoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton tophat_abertura;
    private javax.swing.JRadioButton tophat_fechamento;
    // End of variables declaration//GEN-END:variables
}
