package Telas.Morfologia;

import Model.ImgWindow;
import Processamento.Morfologia;
import java.awt.image.BufferedImage;
import java.io.File;
import Telas.Tela_Principal_;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public class Tela_Reconstrucao extends javax.swing.JFrame {

    // Tipos de aplicacao.
    // Nome do metodo a ser aplicado.
//    public String Metodo_nome = "_Metodo_";
    // Atributos.
    public BufferedImage marcadorBfImg, mascaraBfImg, novaImagem;
    public boolean marcador_carregado, mascara_carregada;
    private File marcador, mascara;
    private Tela_Principal_ telaPrincipal;
    private javax.swing.JInternalFrame[] imagensCarregadas;
    public File Caminho = new File("/home/");
    private int seletor;
    private String nomeOriginalMarcador;

    /**
     * Creates new form TelaPostPasta
     */
    public Tela_Reconstrucao(Tela_Principal_ telaPrincipal, int seletor,javax.swing.JInternalFrame[] imagensCarregadas) {
        initComponents();
        this.seletor = seletor;
        this.telaPrincipal = telaPrincipal;
        this.marcadorBfImg = Morfologia.copyImage(telaPrincipal.getSelectedImg());
        this.nomeOriginalMarcador = telaPrincipal.getSelectedImgName();
        this.imagensCarregadas = imagensCarregadas;
//        buttonGroup2.add(eeCruz);
//        buttonGroup2.add(eeBarraHorizontal);
//        buttonGroup2.add(eeBarraVertical);
//        buttonGroup2.add(eeQuadrado);
//        buttonGroup2.add(eeRhombus);
        
        for (JInternalFrame index : this.imagensCarregadas) {
            if (index instanceof ImgWindow){
                listaDeImagens.addItem(index.getTitle());
            }
        }
        nomeMarcador.setText(telaPrincipal.getSelectedImgName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Cancelar_ = new javax.swing.JButton();
        Aplicar_ = new javax.swing.JButton();
        nomeMarcador = new javax.swing.JLabel();
        nomeMascara = new javax.swing.JLabel();
        listaDeImagens = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reconstrução de imagem em nível de cinza");
        setFocusCycleRoot(false);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reconstrução");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Imagem como marcador:");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Imagem como máscara:");

        Cancelar_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Cancelar_.setText("Cancelar");
        Cancelar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_ActionPerformed(evt);
            }
        });

        Aplicar_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_.setText("Aplicar");
        Aplicar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_ActionPerformed(evt);
            }
        });

        nomeMarcador.setText("[nome do marcador]");

        nomeMascara.setText("[nome da mascara]");

        listaDeImagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDeImagensActionPerformed(evt);
            }
        });
        listaDeImagens.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                listaDeImagensPropertyChange(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Escolha a mascara:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cancelar_, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Aplicar_, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeMascara))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeMarcador))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaDeImagens, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(102, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(listaDeImagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeMarcador))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomeMascara))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar_)
                    .addComponent(Aplicar_))
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*  Metodo para aplicar algoritmos em um lote de imagens.   */
    private void Aplicar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_ActionPerformed
        ArrayList<Point> ElemEst = new ArrayList<>();
        JFrame F = new JFrame();
        ElemEst.add(new Point(-1, -1));
        ElemEst.add(new Point(0, -1));
        ElemEst.add(new Point(1, -1));
        ElemEst.add(new Point(-1, 0));
        ElemEst.add(new Point(0, 0));
        ElemEst.add(new Point(0, 1));
        ElemEst.add(new Point(-1, 1));
        ElemEst.add(new Point(1, 0));
        ElemEst.add(new Point(1, 1));
        
        for (JInternalFrame index : this.imagensCarregadas) {
            if (index instanceof ImgWindow){
                if(index.getTitle().equals((String) listaDeImagens.getSelectedItem())){
                    mascaraBfImg = ((ImgWindow) index).getImg();
                }
            }
        }
        if(!Morfologia.checaCompatibilidade(mascaraBfImg, marcadorBfImg)){
            JOptionPane.showMessageDialog(F, "Não foi possível realizar a reconstrução pois as imagens são de tamanho diferentes");
        }else{
            if(this.seletor==1){
                this.novaImagem = Morfologia.reconstrucaoRapida(mascaraBfImg, marcadorBfImg, ElemEst);
                this.telaPrincipal.openInternalImg(this.novaImagem, this.nomeOriginalMarcador, "_reconstruida");
            }
            if(this.seletor==2){
                this.novaImagem = Morfologia.reconstrucaoDualRapida(mascaraBfImg, marcadorBfImg, ElemEst);
                this.telaPrincipal.openInternalImg(this.novaImagem, this.nomeOriginalMarcador, "_reconstruida_dual");
            }
        }
        this.dispose();

    }//GEN-LAST:event_Aplicar_ActionPerformed

    /*  Metodo para cancelar a aplicacao de algum
        algoritmo em um lote de imagens.    */
    private void Cancelar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_ActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cancelar_ActionPerformed

    private void listaDeImagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDeImagensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaDeImagensActionPerformed

    private void listaDeImagensPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_listaDeImagensPropertyChange
        // TODO add your handling code here:
        nomeMascara.setText((String)listaDeImagens.getSelectedItem());
    }//GEN-LAST:event_listaDeImagensPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Reconstrucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Reconstrucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Reconstrucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Reconstrucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Tela_Reconstrucao(this.telaPrincipal).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aplicar_;
    private javax.swing.JButton Cancelar_;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> listaDeImagens;
    private javax.swing.JLabel nomeMarcador;
    private javax.swing.JLabel nomeMascara;
    // End of variables declaration//GEN-END:variables
}
