package Telas;

import Telas.Segmentacao.Tela_Aplicacao_Lote_Segmentacao;
import Telas.Deteccao_Pele.Tela_Deteccao_Pele_RGB_Norm;
import Telas.Deteccao_Pele.Tela_Deteccao_Pele_YCgCr;
import Telas.Deteccao_Pele.Tela_Deteccao_Pele_Comb;
import Model.ImgWindow;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import Processamento.Processamento_Imagem_;
import Telas.Morfologia.ElementoEstruturante;
import Telas.Deteccao_Pele.Tela_Aplicacao_Lote_Deteccao_Pele;
import java.awt.Color;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;


/**
 * @author João Victor do Rozário Recla - 2022/2
 */
public class Tela_Principal_ extends javax.swing.JFrame {
    
    public File Img_original;
    public boolean Img_carregada;
    public BufferedImage Img_atual;
    public File Caminho = new File("/home/");
    public boolean Img_RI, Img_BI, Img_segmentada;
    
    /**
     * Creates new form TelaPrincipal
     */
    public Tela_Principal_() {
        initComponents();
        jDesktopPane1.setBackground(new Color(230, 235, 240));
        jDesktopPane1.setOpaque(true);
        jDesktopPane1.repaint();
        //jScrollPane1.getViewport().setBackground(Color.GRAY);
    }
    
    public void openInternalImg(BufferedImage img, String title, String sufixo){
               
        ImgWindow window = new ImgWindow(img, title, sufixo);
        
        jDesktopPane1.add(window);
        window.toFront();
        
        try{
            window.setSelected(true);
        }catch(java.beans.PropertyVetoException e){}
    }
    
    public BufferedImage getSelectedImg(){
        JInternalFrame selectedFrame = jDesktopPane1.getSelectedFrame();
        
        if (selectedFrame instanceof ImgWindow){
            return ((ImgWindow) selectedFrame).getImg();
        }
        
        return null;
    }
    
    public String getSelectedImgName(){
        JInternalFrame selectedFrame = jDesktopPane1.getSelectedFrame();
        
        if (selectedFrame instanceof ImgWindow){
            return ((ImgWindow) selectedFrame).getOriginalName();
        }
        
        return null;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Tela_ = new javax.swing.JLabel();
        Menus = new javax.swing.JMenuBar();
        Menu_Arquivo_ = new javax.swing.JMenu();
        Carregar_Imagem_ = new javax.swing.JMenuItem();
        ___Separador_01 = new javax.swing.JPopupMenu.Separator();
        Salvar_ = new javax.swing.JMenuItem();
        ___Separador_03 = new javax.swing.JPopupMenu.Separator();
        Sair_ = new javax.swing.JMenuItem();
        Menu_Deterccao_Pele_ = new javax.swing.JMenu();
        Aplicar_na_Imagem = new javax.swing.JMenu();
        RGB_Normalizado = new javax.swing.JMenuItem();
        ___Separador_8 = new javax.swing.JPopupMenu.Separator();
        YCgCr = new javax.swing.JMenuItem();
        ___Separador_3 = new javax.swing.JPopupMenu.Separator();
        Combinacao = new javax.swing.JMenuItem();
        ___Separador_2 = new javax.swing.JPopupMenu.Separator();
        Aplicar_Lote_ = new javax.swing.JMenuItem();
        Menu_Segmentacao_ = new javax.swing.JMenu();
        Binarizacao_Otsu_ = new javax.swing.JMenu();
        Aplicar_Otsu_Imagem_ = new javax.swing.JMenuItem();
        ___Separador_07 = new javax.swing.JPopupMenu.Separator();
        Aplicar_Otsu_Lote_ = new javax.swing.JMenuItem();
        ___Separador_04 = new javax.swing.JPopupMenu.Separator();
        Binarizacao_Fuzzy_Huang_ = new javax.swing.JMenu();
        Aplicar_FuzzyHuang_Imagem_ = new javax.swing.JMenuItem();
        ___Separador_08 = new javax.swing.JPopupMenu.Separator();
        Aplicar_FuzzyHuang_Lote_ = new javax.swing.JMenuItem();
        menu_morfologia = new javax.swing.JMenu();
        Erosao = new javax.swing.JMenuItem();
        dilatacao = new javax.swing.JMenuItem();
        abertura = new javax.swing.JMenuItem();
        fechamento = new javax.swing.JMenuItem();
        Tophat = new javax.swing.JMenu();
        tophatFechamento = new javax.swing.JMenuItem();
        tophatAbertura = new javax.swing.JMenuItem();
        Menu_Outros_ = new javax.swing.JMenu();
        Sobre_ = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem12.setText("jMenuItem12");

        jMenuItem14.setText("jMenuItem14");

        jMenuItem15.setText("jMenuItem15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Detecção de pele afrodescentes - Matheus Silva Cruz");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);

        Tela_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Tela_.setToolTipText("");
        Tela_.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jDesktopPane1.setLayer(Tela_, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Tela_, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 754, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(Tela_, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        Menus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Menus.setAlignmentY(0.5F);
        Menus.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        Menus.setMargin(new java.awt.Insets(20, 20, 20, 20));
        Menus.setMaximumSize(new java.awt.Dimension(479, 32775));
        Menus.setPreferredSize(new java.awt.Dimension(480, 35));

        Menu_Arquivo_.setBorder(null);
        Menu_Arquivo_.setText("Arquivo");
        Menu_Arquivo_.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu_Arquivo_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Menu_Arquivo_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu_Arquivo_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Menu_Arquivo_.setPreferredSize(new java.awt.Dimension(70, 25));

        Carregar_Imagem_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Carregar_Imagem_.setText("Carregar imagem");
        Carregar_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Carregar_Imagem_.setIconTextGap(0);
        Carregar_Imagem_.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Carregar_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carregar_Imagem_ActionPerformed(evt);
            }
        });
        Menu_Arquivo_.add(Carregar_Imagem_);
        Menu_Arquivo_.add(___Separador_01);

        Salvar_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Salvar_.setText("Salvar");
        Salvar_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Salvar_.setIconTextGap(0);
        Salvar_.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Salvar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar_ActionPerformed(evt);
            }
        });
        Menu_Arquivo_.add(Salvar_);
        Menu_Arquivo_.add(___Separador_03);

        Sair_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Sair_.setText("Sair");
        Sair_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Sair_.setIconTextGap(0);
        Sair_.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair_ActionPerformed(evt);
            }
        });
        Menu_Arquivo_.add(Sair_);

        Menus.add(Menu_Arquivo_);

        Menu_Deterccao_Pele_.setBorder(null);
        Menu_Deterccao_Pele_.setText("Detectar Pele");
        Menu_Deterccao_Pele_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Menu_Deterccao_Pele_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu_Deterccao_Pele_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Menu_Deterccao_Pele_.setPreferredSize(new java.awt.Dimension(120, 17));

        Aplicar_na_Imagem.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 6, 3, 6));
        Aplicar_na_Imagem.setText("Aplicar na Imagem");
        Aplicar_na_Imagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Aplicar_na_Imagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Aplicar_na_Imagem.setPreferredSize(new java.awt.Dimension(170, 25));

        RGB_Normalizado.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        RGB_Normalizado.setText("RGB Normalizado");
        RGB_Normalizado.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        RGB_Normalizado.setPreferredSize(new java.awt.Dimension(170, 25));
        RGB_Normalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGB_NormalizadoActionPerformed(evt);
            }
        });
        Aplicar_na_Imagem.add(RGB_Normalizado);
        Aplicar_na_Imagem.add(___Separador_8);

        YCgCr.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        YCgCr.setText("YCgCr");
        YCgCr.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        YCgCr.setPreferredSize(new java.awt.Dimension(170, 25));
        YCgCr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YCgCrActionPerformed(evt);
            }
        });
        Aplicar_na_Imagem.add(YCgCr);
        Aplicar_na_Imagem.add(___Separador_3);

        Combinacao.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        Combinacao.setText("Combinação");
        Combinacao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Combinacao.setPreferredSize(new java.awt.Dimension(170, 25));
        Combinacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombinacaoActionPerformed(evt);
            }
        });
        Aplicar_na_Imagem.add(Combinacao);

        Menu_Deterccao_Pele_.add(Aplicar_na_Imagem);
        Menu_Deterccao_Pele_.add(___Separador_2);

        Aplicar_Lote_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Aplicar_Lote_.setText("Aplicar em lote");
        Aplicar_Lote_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Aplicar_Lote_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_Lote_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_Lote_ActionPerformed(evt);
            }
        });
        Menu_Deterccao_Pele_.add(Aplicar_Lote_);

        Menus.add(Menu_Deterccao_Pele_);

        Menu_Segmentacao_.setBorder(null);
        Menu_Segmentacao_.setText("Segmentação");
        Menu_Segmentacao_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Menu_Segmentacao_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu_Segmentacao_.setPreferredSize(new java.awt.Dimension(100, 17));

        Binarizacao_Otsu_.setBorder(null);
        Binarizacao_Otsu_.setText("Binarização de Otsu");
        Binarizacao_Otsu_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Binarizacao_Otsu_.setPreferredSize(new java.awt.Dimension(200, 25));

        Aplicar_Otsu_Imagem_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Aplicar_Otsu_Imagem_.setText("Aplicar na imagem");
        Aplicar_Otsu_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Aplicar_Otsu_Imagem_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_Otsu_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_Otsu_Imagem_ActionPerformed(evt);
            }
        });
        Binarizacao_Otsu_.add(Aplicar_Otsu_Imagem_);
        Binarizacao_Otsu_.add(___Separador_07);

        Aplicar_Otsu_Lote_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Aplicar_Otsu_Lote_.setText("Aplicar em lote");
        Aplicar_Otsu_Lote_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Aplicar_Otsu_Lote_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_Otsu_Lote_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_Otsu_Lote_ActionPerformed(evt);
            }
        });
        Binarizacao_Otsu_.add(Aplicar_Otsu_Lote_);

        Menu_Segmentacao_.add(Binarizacao_Otsu_);
        Menu_Segmentacao_.add(___Separador_04);

        Binarizacao_Fuzzy_Huang_.setBorder(null);
        Binarizacao_Fuzzy_Huang_.setText("Bin Fuzzy de Huang");
        Binarizacao_Fuzzy_Huang_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Binarizacao_Fuzzy_Huang_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Binarizacao_Fuzzy_Huang_.setPreferredSize(new java.awt.Dimension(170, 25));

        Aplicar_FuzzyHuang_Imagem_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Aplicar_FuzzyHuang_Imagem_.setText("Aplicar na imagem");
        Aplicar_FuzzyHuang_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Aplicar_FuzzyHuang_Imagem_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_FuzzyHuang_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_FuzzyHuang_Imagem_ActionPerformed(evt);
            }
        });
        Binarizacao_Fuzzy_Huang_.add(Aplicar_FuzzyHuang_Imagem_);
        Binarizacao_Fuzzy_Huang_.add(___Separador_08);

        Aplicar_FuzzyHuang_Lote_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Aplicar_FuzzyHuang_Lote_.setText("Aplicar em lote");
        Aplicar_FuzzyHuang_Lote_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Aplicar_FuzzyHuang_Lote_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_FuzzyHuang_Lote_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_FuzzyHuang_Lote_ActionPerformed(evt);
            }
        });
        Binarizacao_Fuzzy_Huang_.add(Aplicar_FuzzyHuang_Lote_);

        Menu_Segmentacao_.add(Binarizacao_Fuzzy_Huang_);

        Menus.add(Menu_Segmentacao_);

        menu_morfologia.setToolTipText("");
        menu_morfologia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_morfologia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_morfologia.setLabel("Morfologia");

        Erosao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Erosao.setText("Erosão");
        Erosao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErosaoActionPerformed(evt);
            }
        });
        menu_morfologia.add(Erosao);

        dilatacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dilatacao.setText("Dilatação");
        menu_morfologia.add(dilatacao);

        abertura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        abertura.setText("Abertura");
        menu_morfologia.add(abertura);

        fechamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fechamento.setText("Fechamento");
        menu_morfologia.add(fechamento);

        Tophat.setText("Tophat");
        Tophat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tophatFechamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tophatFechamento.setText("Tophat de abertura");
        Tophat.add(tophatFechamento);

        tophatAbertura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tophatAbertura.setText("Tophat de fechamento");
        Tophat.add(tophatAbertura);

        menu_morfologia.add(Tophat);

        Menus.add(menu_morfologia);

        Menu_Outros_.setBorder(null);
        Menu_Outros_.setText("Outros");
        Menu_Outros_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Menu_Outros_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu_Outros_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Menu_Outros_.setMinimumSize(new java.awt.Dimension(60, 25));
        Menu_Outros_.setPreferredSize(new java.awt.Dimension(70, 25));

        Sobre_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Sobre_.setText("Sobre o software");
        Sobre_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Sobre_.setPreferredSize(new java.awt.Dimension(170, 25));
        Sobre_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sobre_ActionPerformed(evt);
            }
        });
        Menu_Outros_.add(Sobre_);

        Menus.add(Menu_Outros_);

        setJMenuBar(Menus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /*  Metodo para carregar uma imagem para o sistema. */
    private void Carregar_Imagem_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carregar_Imagem_ActionPerformed

        // Configura e abre uma janela de dialogo.
        JFileChooser Fs = new JFileChooser(Caminho);
        Fs.setFileFilter(new FileNameExtensionFilter("Arquivos de Imagem (png, jpg, jpeg, bmp)", "png", "jpg", "jpeg", "bmp"));
        Fs.setAcceptAllFileFilterUsed(false);
        Fs.setDialogTitle("Selecione um arquivo de imagem...");
        int Retorno = Fs.showOpenDialog(this);
        
        // Seleciona a imagem.
        if(Retorno == JFileChooser.APPROVE_OPTION){
            
            try {
                // Carrega a imagem para o sistema.
                Img_original = Fs.getSelectedFile();
                Img_atual    = ImageIO.read(Img_original);
                
                String nameWithoutExtension = Img_original.getName().replaceFirst("\\.[^.]+$", "");
                openInternalImg(Img_atual, nameWithoutExtension, "");

                Img_carregada = true;

                // Atualiza o caminho com o diretorio da pasta selecionada.
                Caminho = Fs.getCurrentDirectory();
            } catch (IOException ex) {
                Logger.getLogger(Tela_Principal_.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Carregar_Imagem_ActionPerformed

    
    /*  Metodo para salvar uma imagem.  */
    private void Salvar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar_ActionPerformed
        
        JFrame F = new JFrame();
        
        JInternalFrame selectedFrame = jDesktopPane1.getSelectedFrame();
        
        
        if (selectedFrame instanceof ImgWindow) {
            ImgWindow imgWindow = (ImgWindow) selectedFrame;
            
            BufferedImage img = imgWindow.getImg();
            String name = imgWindow.getOriginalName();
            
            if (img != null){
                JFileChooser Fs = new JFileChooser();
                Fs.setFileFilter(new FileNameExtensionFilter("PNG Images", "png"));
                Fs.setDialogTitle("Escolha onde salvar a imagem processada...");
                Fs.setSelectedFile(new File(name + ".png"));
                int response = Fs.showSaveDialog(this);
                
                if(response == JFileChooser.APPROVE_OPTION){
                    
                    File Fo = Fs.getSelectedFile();
                    if (!Fo.getName().toLowerCase().endsWith(".png")) {
                        Fo = new File(Fo.getAbsolutePath() + ".png");
                    }
                    
                    try {
                        ImageIO.write(img, "png", Fo);
                        JOptionPane.showMessageDialog(F, "Imagem salva com sucesso.");
                    } catch (IOException e){
                        JOptionPane.showMessageDialog(F, "Não foi possível salvar a imagem!");
                        Logger.getLogger(Tela_Principal_.class.getName()).log(Level.SEVERE, null, e);
                    }
                }

            } else {
                JOptionPane.showMessageDialog(F, "Não há imagem nessa janela!");
            }
            
        } else {
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada ou nenhuma janela ativa!");
        }
    }//GEN-LAST:event_Salvar_ActionPerformed

    
    
    /*  Metodo para exibir as informacoes sobre o software. */
    private void Sobre_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sobre_ActionPerformed
        
        JFrame F = new JFrame();
        JOptionPane.showMessageDialog(F, "Programa desenvolvido e implementado por Matheus Silva Cruz     "
                                       + "\nem 2025/1, na disciplina de PDI ministrada pelo Prof. Jacques Facon.");
    }//GEN-LAST:event_Sobre_ActionPerformed

    
    /*  Metodo para sair do sistema.    */
    private void Sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair_ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Sair_ActionPerformed

    
    
    
    /*  Metodo para aplicar o algoritmo de segmentacao
        "Binarizacao Otsu" em um lote de imagens.   */
    private void Aplicar_Otsu_Lote_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_Otsu_Lote_ActionPerformed
        
        Tela_Aplicacao_Lote_Segmentacao Tela = new Tela_Aplicacao_Lote_Segmentacao();
        Tela.setLocationRelativeTo(null);
        Tela.Aplicar_segmentacao = true;
        Tela.Metodo_nome         = "_BinarizacaoOtsu";
        Tela.Segmentacao_tipo    = 1;
        Tela.setVisible(true);
    }//GEN-LAST:event_Aplicar_Otsu_Lote_ActionPerformed

    
    /*  Metodo para aplicar o algoritmo de segmentacao
        "Binarizacao Otsu" em uma imagem.   */
    private void Aplicar_Otsu_Imagem_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_Otsu_Imagem_ActionPerformed
        
        JFrame F = new JFrame();
        
        if(Img_carregada){
            
            try{
                
                // Aplica o algoritmo na imagem atual.
                BufferedImage Img_processada = Processamento_Imagem_.Segment_(Img_atual, 1);
                
                if(Img_processada == null) {
                    
                    JOptionPane.showMessageDialog(F, "Não foi possível aplicar a segmentação!");
                }else{
                    
                    openInternalImg(Img_processada, this.getSelectedImgName(), "_Otsu");
                    Img_segmentada = true;
                }
            }catch( NullPointerException | IllegalArgumentException ex){
                
                JOptionPane.showMessageDialog(F, "Não foi possível aplicar a segmentação!");
                Logger.getLogger(Tela_Principal_.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        }
    }//GEN-LAST:event_Aplicar_Otsu_Imagem_ActionPerformed

    
    
    
    
    /*  Metodo para aplicar o algoritmo de segmentacao
        "Binarizacao Fuzzy Huang" em uma imagem.    */
    private void Aplicar_FuzzyHuang_Imagem_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_FuzzyHuang_Imagem_ActionPerformed
        
        JFrame F = new JFrame();
        
        if(Img_carregada){
            
            try{
                
                // Aplica o algoritmo na imagem atual.
                BufferedImage Img_processada = Processamento_Imagem_.Segment_(Img_atual, 2);
                
                if(Img_processada == null) {
                    
                    JOptionPane.showMessageDialog(F, "Não foi possível aplicar a segmentação!");
                }else{
                    openInternalImg(Img_processada, this.getSelectedImgName(), "_FuzzyHuang");
                    Img_segmentada = true;
                }
            }catch(NullPointerException | IllegalArgumentException ex){
                
                JOptionPane.showMessageDialog(F, "Não foi possível aplicar a segmentação!");
                Logger.getLogger(Tela_Principal_.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        }
    }//GEN-LAST:event_Aplicar_FuzzyHuang_Imagem_ActionPerformed

    
    /*  Metodo para aplicar o algoritmo de segmentacao
        "Binarizacao Fuzzy Huang" em um lote de imagens.    */
    private void Aplicar_FuzzyHuang_Lote_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_FuzzyHuang_Lote_ActionPerformed
        
        Tela_Aplicacao_Lote_Segmentacao Tela = new Tela_Aplicacao_Lote_Segmentacao();
        Tela.setLocationRelativeTo(null);
        Tela.Aplicar_segmentacao = true;
        Tela.Metodo_nome         = "_BinFuzHuang";
        Tela.Segmentacao_tipo    = 2;
        Tela.setVisible(true);
    }//GEN-LAST:event_Aplicar_FuzzyHuang_Lote_ActionPerformed

    private void RGB_NormalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGB_NormalizadoActionPerformed
        // TODO add your handling code here:
        JFrame F = new JFrame();
        
        if(Img_carregada){
            Tela_Deteccao_Pele_RGB_Norm Tela = new Tela_Deteccao_Pele_RGB_Norm(this);
            Tela.setLocationRelativeTo(null);
            Tela.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        }
        
    }//GEN-LAST:event_RGB_NormalizadoActionPerformed

    private void Aplicar_Lote_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_Lote_ActionPerformed
        Tela_Aplicacao_Lote_Deteccao_Pele Tela = new Tela_Aplicacao_Lote_Deteccao_Pele();
        Tela.setLocationRelativeTo(null);
        Tela.setVisible(true);
    }//GEN-LAST:event_Aplicar_Lote_ActionPerformed

    private void YCgCrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YCgCrActionPerformed
        // TODO add your handling code here:
        JFrame F = new JFrame();
        
        if(Img_carregada){
            
            Tela_Deteccao_Pele_YCgCr Tela = new Tela_Deteccao_Pele_YCgCr(this);
            Tela.setLocationRelativeTo(null);
            Tela.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        }
    }//GEN-LAST:event_YCgCrActionPerformed

    private void CombinacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombinacaoActionPerformed
        // TODO add your handling code here:
        JFrame F = new JFrame();
        
        if(Img_carregada){
            
            Tela_Deteccao_Pele_Comb Tela = new Tela_Deteccao_Pele_Comb(this);
            Tela.setLocationRelativeTo(null);
            Tela.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        }
    }//GEN-LAST:event_CombinacaoActionPerformed

    private void ErosaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErosaoActionPerformed
        // TODO add your handling code here:
        JFrame F = new JFrame();
        if(Img_carregada){
            ElementoEstruturante janelaEE = new ElementoEstruturante(this);
            janelaEE.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        }   
    }//GEN-LAST:event_ErosaoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("FlatLaf".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Tela_Principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Tela_Principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Tela_Principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Tela_Principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal_().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Aplicar_FuzzyHuang_Imagem_;
    private javax.swing.JMenuItem Aplicar_FuzzyHuang_Lote_;
    private javax.swing.JMenuItem Aplicar_Lote_;
    private javax.swing.JMenuItem Aplicar_Otsu_Imagem_;
    private javax.swing.JMenuItem Aplicar_Otsu_Lote_;
    private javax.swing.JMenu Aplicar_na_Imagem;
    private javax.swing.JMenu Binarizacao_Fuzzy_Huang_;
    private javax.swing.JMenu Binarizacao_Otsu_;
    private javax.swing.JMenuItem Carregar_Imagem_;
    private javax.swing.JMenuItem Combinacao;
    private javax.swing.JMenuItem Erosao;
    private javax.swing.JMenu Menu_Arquivo_;
    private javax.swing.JMenu Menu_Deterccao_Pele_;
    private javax.swing.JMenu Menu_Outros_;
    private javax.swing.JMenu Menu_Segmentacao_;
    private javax.swing.JMenuBar Menus;
    private javax.swing.JMenuItem RGB_Normalizado;
    private javax.swing.JMenuItem Sair_;
    private javax.swing.JMenuItem Salvar_;
    private javax.swing.JMenuItem Sobre_;
    private javax.swing.JLabel Tela_;
    private javax.swing.JMenu Tophat;
    private javax.swing.JMenuItem YCgCr;
    private javax.swing.JPopupMenu.Separator ___Separador_01;
    private javax.swing.JPopupMenu.Separator ___Separador_03;
    private javax.swing.JPopupMenu.Separator ___Separador_04;
    private javax.swing.JPopupMenu.Separator ___Separador_07;
    private javax.swing.JPopupMenu.Separator ___Separador_08;
    private javax.swing.JPopupMenu.Separator ___Separador_2;
    private javax.swing.JPopupMenu.Separator ___Separador_3;
    private javax.swing.JPopupMenu.Separator ___Separador_8;
    private javax.swing.JMenuItem abertura;
    private javax.swing.JMenuItem dilatacao;
    private javax.swing.JMenuItem fechamento;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu menu_morfologia;
    private javax.swing.JMenuItem tophatAbertura;
    private javax.swing.JMenuItem tophatFechamento;
    // End of variables declaration//GEN-END:variables
}
