package Telas;

import Telas.Segmentacao.Tela_Aplicacao_Lote_Segmentacao;
import Model.ImgWindow;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import Processamento.Processamento_Imagem_;
import Telas.Morfologia.ElementoEstruturante;
import java.awt.Color;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;
import Telas.Morfologia.Tela_Aplicacao_Lote_Morfologia;
import Telas.Morfologia.Tela_Reconstrucao;
import Processamento.Morfologia;


/**
 * @author João Victor do Rozário Recla - 2022/2
 */
public class Tela_Principal_ extends javax.swing.JFrame {
    
    public File Img_original;
    public boolean Img_carregada;
    public BufferedImage Img_atual;
    public File Caminho = new File("/home/");
    public boolean Img_RI, Img_BI, Img_segmentada;
    
    /**
     * Creates new form TelaPrincipal
     */
    public Tela_Principal_() {
        initComponents();
        jDesktopPane1.setBackground(new Color(230, 235, 240));
        jDesktopPane1.setOpaque(true);
        jDesktopPane1.repaint();
        //jScrollPane1.getViewport().setBackground(Color.GRAY);
    }
    
    public void openInternalImg(BufferedImage img, String title, String sufixo){
               
        ImgWindow window = new ImgWindow(img, title, sufixo);
        
        jDesktopPane1.add(window);
        window.toFront();
        
        try{
            window.setSelected(true);
        }catch(java.beans.PropertyVetoException e){}
    }
    
    public BufferedImage getSelectedImg(){
        JInternalFrame selectedFrame = jDesktopPane1.getSelectedFrame();
        
        if (selectedFrame instanceof ImgWindow){
            return ((ImgWindow) selectedFrame).getImg();
        }
        
        return null;
    }
    
    public String getSelectedImgName(){
        JInternalFrame selectedFrame = jDesktopPane1.getSelectedFrame();
        
        if (selectedFrame instanceof ImgWindow){
            return ((ImgWindow) selectedFrame).getOriginalName();
        }
        
        return null;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Tela_ = new javax.swing.JLabel();
        Menus = new javax.swing.JMenuBar();
        Menu_Arquivo_ = new javax.swing.JMenu();
        Carregar_Imagem_ = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Salvar_ = new javax.swing.JMenuItem();
        ___Separador_03 = new javax.swing.JPopupMenu.Separator();
        Sair_ = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        inverterImagem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        bordaCinza = new javax.swing.JMenuItem();
        Menu_Segmentacao_ = new javax.swing.JMenu();
        Binarizacao_Otsu_ = new javax.swing.JMenu();
        Aplicar_Otsu_Imagem_ = new javax.swing.JMenuItem();
        ___Separador_07 = new javax.swing.JPopupMenu.Separator();
        Aplicar_Otsu_Lote_ = new javax.swing.JMenuItem();
        ___Separador_04 = new javax.swing.JPopupMenu.Separator();
        Binarizacao_Fuzzy_Huang_ = new javax.swing.JMenu();
        Aplicar_FuzzyHuang_Imagem_ = new javax.swing.JMenuItem();
        ___Separador_08 = new javax.swing.JPopupMenu.Separator();
        Aplicar_FuzzyHuang_Lote_ = new javax.swing.JMenuItem();
        menu_morfologia = new javax.swing.JMenu();
        Erosao = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        dilatacao = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        abertura = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        fechamento = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        Tophat = new javax.swing.JMenu();
        tophatAber = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        tophatFecha = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        reconstrucaoRapida = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        recostrucaoDualRapida = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        Menu_Outros_ = new javax.swing.JMenu();
        Sobre_ = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem12.setText("jMenuItem12");

        jMenuItem14.setText("jMenuItem14");

        jMenuItem15.setText("jMenuItem15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plataforma de processamento de imagens nível de cinza com morfologia matemática");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);

        Tela_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Tela_.setToolTipText("");
        Tela_.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jDesktopPane1.setLayer(Tela_, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(0, 120, Short.MAX_VALUE)
                    .addComponent(Tela_, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 873, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(Tela_, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        Menus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Menus.setAlignmentY(0.5F);
        Menus.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        Menus.setMargin(new java.awt.Insets(20, 20, 20, 20));
        Menus.setMaximumSize(new java.awt.Dimension(479, 32775));
        Menus.setPreferredSize(new java.awt.Dimension(480, 35));

        Menu_Arquivo_.setBorder(null);
        Menu_Arquivo_.setText("Arquivo");
        Menu_Arquivo_.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu_Arquivo_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Menu_Arquivo_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu_Arquivo_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Menu_Arquivo_.setMinimumSize(new java.awt.Dimension(60, 25));
        Menu_Arquivo_.setPreferredSize(new java.awt.Dimension(70, 25));

        Carregar_Imagem_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Carregar_Imagem_.setText("Carregar imagem");
        Carregar_Imagem_.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Carregar_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Carregar_Imagem_.setIconTextGap(0);
        Carregar_Imagem_.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Carregar_Imagem_.setMinimumSize(new java.awt.Dimension(150, 22));
        Carregar_Imagem_.setPreferredSize(new java.awt.Dimension(200, 22));
        Carregar_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carregar_Imagem_ActionPerformed(evt);
            }
        });
        Menu_Arquivo_.add(Carregar_Imagem_);
        Menu_Arquivo_.add(jSeparator1);

        Salvar_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Salvar_.setText("Salvar");
        Salvar_.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Salvar_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Salvar_.setIconTextGap(0);
        Salvar_.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Salvar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar_ActionPerformed(evt);
            }
        });
        Menu_Arquivo_.add(Salvar_);
        Menu_Arquivo_.add(___Separador_03);

        Sair_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Sair_.setText("Sair");
        Sair_.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Sair_.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sair_.setIconTextGap(0);
        Sair_.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair_ActionPerformed(evt);
            }
        });
        Menu_Arquivo_.add(Sair_);

        Menus.add(Menu_Arquivo_);

        jMenu1.setBorder(null);
        jMenu1.setText("Imagem");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenu1.setPreferredSize(new java.awt.Dimension(60, 20));

        inverterImagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inverterImagem.setText("Inverter imagem");
        inverterImagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inverterImagem.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        inverterImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inverterImagemActionPerformed(evt);
            }
        });
        jMenu1.add(inverterImagem);
        jMenu1.add(jSeparator2);

        bordaCinza.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bordaCinza.setText("Borda cinza/Centro preto");
        bordaCinza.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bordaCinza.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        bordaCinza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bordaCinzaActionPerformed(evt);
            }
        });
        jMenu1.add(bordaCinza);

        Menus.add(jMenu1);

        Menu_Segmentacao_.setBorder(null);
        Menu_Segmentacao_.setText("Segmentação");
        Menu_Segmentacao_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Menu_Segmentacao_.setPreferredSize(new java.awt.Dimension(90, 17));

        Binarizacao_Otsu_.setBorder(null);
        Binarizacao_Otsu_.setText("Binarização de Otsu");
        Binarizacao_Otsu_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Binarizacao_Otsu_.setPreferredSize(new java.awt.Dimension(200, 25));

        Aplicar_Otsu_Imagem_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Aplicar_Otsu_Imagem_.setText("Aplicar na imagem");
        Aplicar_Otsu_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Aplicar_Otsu_Imagem_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_Otsu_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_Otsu_Imagem_ActionPerformed(evt);
            }
        });
        Binarizacao_Otsu_.add(Aplicar_Otsu_Imagem_);
        Binarizacao_Otsu_.add(___Separador_07);

        Aplicar_Otsu_Lote_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Aplicar_Otsu_Lote_.setText("Aplicar em lote");
        Aplicar_Otsu_Lote_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Aplicar_Otsu_Lote_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_Otsu_Lote_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_Otsu_Lote_ActionPerformed(evt);
            }
        });
        Binarizacao_Otsu_.add(Aplicar_Otsu_Lote_);

        Menu_Segmentacao_.add(Binarizacao_Otsu_);
        Menu_Segmentacao_.add(___Separador_04);

        Binarizacao_Fuzzy_Huang_.setBorder(null);
        Binarizacao_Fuzzy_Huang_.setText("Bin Fuzzy de Huang");
        Binarizacao_Fuzzy_Huang_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Binarizacao_Fuzzy_Huang_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Binarizacao_Fuzzy_Huang_.setPreferredSize(new java.awt.Dimension(170, 25));

        Aplicar_FuzzyHuang_Imagem_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Aplicar_FuzzyHuang_Imagem_.setText("Aplicar na imagem");
        Aplicar_FuzzyHuang_Imagem_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Aplicar_FuzzyHuang_Imagem_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_FuzzyHuang_Imagem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_FuzzyHuang_Imagem_ActionPerformed(evt);
            }
        });
        Binarizacao_Fuzzy_Huang_.add(Aplicar_FuzzyHuang_Imagem_);
        Binarizacao_Fuzzy_Huang_.add(___Separador_08);

        Aplicar_FuzzyHuang_Lote_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Aplicar_FuzzyHuang_Lote_.setText("Aplicar em lote");
        Aplicar_FuzzyHuang_Lote_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Aplicar_FuzzyHuang_Lote_.setPreferredSize(new java.awt.Dimension(150, 25));
        Aplicar_FuzzyHuang_Lote_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_FuzzyHuang_Lote_ActionPerformed(evt);
            }
        });
        Binarizacao_Fuzzy_Huang_.add(Aplicar_FuzzyHuang_Lote_);

        Menu_Segmentacao_.add(Binarizacao_Fuzzy_Huang_);

        Menus.add(Menu_Segmentacao_);

        menu_morfologia.setBorder(null);
        menu_morfologia.setText("Morfologia");
        menu_morfologia.setToolTipText("");
        menu_morfologia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu_morfologia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_morfologia.setPreferredSize(new java.awt.Dimension(80, 20));

        Erosao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Erosao.setText("Erosão");
        Erosao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErosaoActionPerformed(evt);
            }
        });
        menu_morfologia.add(Erosao);
        menu_morfologia.add(jSeparator3);

        dilatacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dilatacao.setText("Dilatação");
        dilatacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dilatacaoActionPerformed(evt);
            }
        });
        menu_morfologia.add(dilatacao);
        menu_morfologia.add(jSeparator4);

        abertura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        abertura.setText("Abertura");
        abertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aberturaActionPerformed(evt);
            }
        });
        menu_morfologia.add(abertura);
        menu_morfologia.add(jSeparator5);

        fechamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fechamento.setText("Fechamento");
        fechamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechamentoActionPerformed(evt);
            }
        });
        menu_morfologia.add(fechamento);
        menu_morfologia.add(jSeparator6);

        Tophat.setText("Tophat");
        Tophat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tophatAber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tophatAber.setText("Tophat de abertura");
        tophatAber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tophatAberActionPerformed(evt);
            }
        });
        Tophat.add(tophatAber);
        Tophat.add(jSeparator10);

        tophatFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tophatFecha.setText("Tophat de fechamento");
        tophatFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tophatFechaActionPerformed(evt);
            }
        });
        Tophat.add(tophatFecha);

        menu_morfologia.add(Tophat);
        menu_morfologia.add(jSeparator7);

        jMenu2.setText("Reconstrução");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        reconstrucaoRapida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reconstrucaoRapida.setText("Reconstrução rápida");
        reconstrucaoRapida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reconstrucaoRapidaActionPerformed(evt);
            }
        });
        jMenu2.add(reconstrucaoRapida);
        jMenu2.add(jSeparator9);

        recostrucaoDualRapida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        recostrucaoDualRapida.setText("Reconstrução dual rápida");
        recostrucaoDualRapida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recostrucaoDualRapidaActionPerformed(evt);
            }
        });
        jMenu2.add(recostrucaoDualRapida);

        menu_morfologia.add(jMenu2);
        menu_morfologia.add(jSeparator8);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setText("Aplicação em lote");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_morfologia.add(jMenuItem1);

        Menus.add(menu_morfologia);

        Menu_Outros_.setBorder(null);
        Menu_Outros_.setText("Outros");
        Menu_Outros_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Menu_Outros_.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Menu_Outros_.setMinimumSize(new java.awt.Dimension(60, 25));
        Menu_Outros_.setPreferredSize(new java.awt.Dimension(60, 25));

        Sobre_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Sobre_.setText("Sobre o software");
        Sobre_.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Sobre_.setPreferredSize(new java.awt.Dimension(170, 25));
        Sobre_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sobre_ActionPerformed(evt);
            }
        });
        Menu_Outros_.add(Sobre_);

        Menus.add(Menu_Outros_);

        setJMenuBar(Menus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /*  Metodo para carregar uma imagem para o sistema. */
    private void Carregar_Imagem_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carregar_Imagem_ActionPerformed

        // Configura e abre uma janela de dialogo.
        JFileChooser Fs = new JFileChooser(Caminho);
        Fs.setFileFilter(new FileNameExtensionFilter("Arquivos de Imagem (png, jpg, jpeg, bmp)", "png", "jpg", "jpeg", "bmp"));
        Fs.setAcceptAllFileFilterUsed(false);
        Fs.setDialogTitle("Selecione um arquivo de imagem...");
        int Retorno = Fs.showOpenDialog(this);
        
        // Seleciona a imagem.
        if(Retorno == JFileChooser.APPROVE_OPTION){
            
            try {
                // Carrega a imagem para o sistema.
                Img_original = Fs.getSelectedFile();
                Img_atual    = ImageIO.read(Img_original);
                
                String nameWithoutExtension = Img_original.getName().replaceFirst("\\.[^.]+$", "");
                openInternalImg(Img_atual, nameWithoutExtension, "");

                Img_carregada = true;

                // Atualiza o caminho com o diretorio da pasta selecionada.
                Caminho = Fs.getCurrentDirectory();
            } catch (IOException ex) {
                Logger.getLogger(Tela_Principal_.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Carregar_Imagem_ActionPerformed

    
    /*  Metodo para salvar uma imagem.  */
    private void Salvar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar_ActionPerformed
        
        JFrame F = new JFrame();
        
        JInternalFrame selectedFrame = jDesktopPane1.getSelectedFrame();
        
        
        if (selectedFrame instanceof ImgWindow) {
            ImgWindow imgWindow = (ImgWindow) selectedFrame;
            
            BufferedImage img = imgWindow.getImg();
            String name = imgWindow.getOriginalName();
            
            if (img != null){
                JFileChooser Fs = new JFileChooser();
                Fs.setFileFilter(new FileNameExtensionFilter("PNG Images", "png"));
                Fs.setDialogTitle("Escolha onde salvar a imagem processada...");
                Fs.setSelectedFile(new File(name + ".png"));
                int response = Fs.showSaveDialog(this);
                
                if(response == JFileChooser.APPROVE_OPTION){
                    
                    File Fo = Fs.getSelectedFile();
                    if (!Fo.getName().toLowerCase().endsWith(".png")) {
                        Fo = new File(Fo.getAbsolutePath() + ".png");
                    }
                    
                    try {
                        ImageIO.write(img, "png", Fo);
                        JOptionPane.showMessageDialog(F, "Imagem salva com sucesso.");
                    } catch (IOException e){
                        JOptionPane.showMessageDialog(F, "Não foi possível salvar a imagem!");
                        Logger.getLogger(Tela_Principal_.class.getName()).log(Level.SEVERE, null, e);
                    }
                }

            } else {
                JOptionPane.showMessageDialog(F, "Não há imagem nessa janela!");
            }
            
        } else {
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada ou nenhuma janela ativa!");
        }
    }//GEN-LAST:event_Salvar_ActionPerformed

    
    
    /*  Metodo para exibir as informacoes sobre o software. */
    private void Sobre_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sobre_ActionPerformed
        
        JFrame F = new JFrame();
        JOptionPane.showMessageDialog(F, "Programa desenvolvido e implementado por Eloy Carlos     "
                                       + "\nem 2025/2, no Projeto de graduação orientado pelo Prof. Jacques Facon.");
    }//GEN-LAST:event_Sobre_ActionPerformed

    
    /*  Metodo para sair do sistema.    */
    private void Sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair_ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Sair_ActionPerformed

    
    
    
    /*  Metodo para aplicar o algoritmo de segmentacao
        "Binarizacao Otsu" em um lote de imagens.   */
    private void Aplicar_Otsu_Lote_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_Otsu_Lote_ActionPerformed
        
        Tela_Aplicacao_Lote_Segmentacao Tela = new Tela_Aplicacao_Lote_Segmentacao();
        Tela.setLocationRelativeTo(null);
        Tela.Aplicar_segmentacao = true;
        Tela.Metodo_nome         = "_BinarizacaoOtsu";
        Tela.Segmentacao_tipo    = 1;
        Tela.setVisible(true);
    }//GEN-LAST:event_Aplicar_Otsu_Lote_ActionPerformed

    
    /*  Metodo para aplicar o algoritmo de segmentacao
        "Binarizacao Otsu" em uma imagem.   */
    private void Aplicar_Otsu_Imagem_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_Otsu_Imagem_ActionPerformed
        
        JFrame F = new JFrame();
        
        if(Img_carregada){
            
            try{
                
                // Aplica o algoritmo na imagem atual.
                BufferedImage Img_processada = Processamento_Imagem_.Segment_(Img_atual, 1);
                
                if(Img_processada == null) {
                    
                    JOptionPane.showMessageDialog(F, "Não foi possível aplicar a segmentação!");
                }else{
                    
                    openInternalImg(Img_processada, this.getSelectedImgName(), "_Otsu");
                    Img_segmentada = true;
                }
            }catch( NullPointerException | IllegalArgumentException ex){
                
                JOptionPane.showMessageDialog(F, "Não foi possível aplicar a segmentação!");
                Logger.getLogger(Tela_Principal_.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        }
    }//GEN-LAST:event_Aplicar_Otsu_Imagem_ActionPerformed

    
    
    
    
    /*  Metodo para aplicar o algoritmo de segmentacao
        "Binarizacao Fuzzy Huang" em uma imagem.    */
    private void Aplicar_FuzzyHuang_Imagem_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_FuzzyHuang_Imagem_ActionPerformed
        
        JFrame F = new JFrame();
        
        if(Img_carregada){
            
            try{
                
                // Aplica o algoritmo na imagem atual.
                BufferedImage Img_processada = Processamento_Imagem_.Segment_(Img_atual, 2);
                
                if(Img_processada == null) {
                    
                    JOptionPane.showMessageDialog(F, "Não foi possível aplicar a segmentação!");
                }else{
                    openInternalImg(Img_processada, this.getSelectedImgName(), "_FuzzyHuang");
                    Img_segmentada = true;
                }
            }catch(NullPointerException | IllegalArgumentException ex){
                
                JOptionPane.showMessageDialog(F, "Não foi possível aplicar a segmentação!");
                Logger.getLogger(Tela_Principal_.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        }
    }//GEN-LAST:event_Aplicar_FuzzyHuang_Imagem_ActionPerformed

    
    /*  Metodo para aplicar o algoritmo de segmentacao
        "Binarizacao Fuzzy Huang" em um lote de imagens.    */
    private void Aplicar_FuzzyHuang_Lote_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_FuzzyHuang_Lote_ActionPerformed
        
        Tela_Aplicacao_Lote_Segmentacao Tela = new Tela_Aplicacao_Lote_Segmentacao();
        Tela.setLocationRelativeTo(null);
        Tela.Aplicar_segmentacao = true;
        Tela.Metodo_nome         = "_BinFuzHuang";
        Tela.Segmentacao_tipo    = 2;
        Tela.setVisible(true);
    }//GEN-LAST:event_Aplicar_FuzzyHuang_Lote_ActionPerformed

    private void ErosaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErosaoActionPerformed
        // TODO add your handling code here:
        JFrame F = new JFrame();
        if(Img_carregada){
            ElementoEstruturante janelaEE = new ElementoEstruturante(this, 1);
            janelaEE.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        }   
    }//GEN-LAST:event_ErosaoActionPerformed

    private void dilatacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dilatacaoActionPerformed
        // TODO add your handling code here:
        JFrame F = new JFrame();
        if(Img_carregada){
            ElementoEstruturante janelaEE = new ElementoEstruturante(this, 2);
            janelaEE.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        } 
    }//GEN-LAST:event_dilatacaoActionPerformed

    private void aberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aberturaActionPerformed
        // TODO add your handling code here:
        JFrame F = new JFrame();
        if(Img_carregada){
            ElementoEstruturante janelaEE = new ElementoEstruturante(this, 3);
            janelaEE.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        } 
    }//GEN-LAST:event_aberturaActionPerformed

    private void fechamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechamentoActionPerformed
        // TODO add your handling code here:
        JFrame F = new JFrame();
        if(Img_carregada){
            ElementoEstruturante janelaEE = new ElementoEstruturante(this, 4);
            janelaEE.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        } 
    }//GEN-LAST:event_fechamentoActionPerformed

    private void tophatAberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tophatAberActionPerformed
        // TODO add your handling code here:
        JFrame F = new JFrame();
        if(Img_carregada){
            ElementoEstruturante janelaEE = new ElementoEstruturante(this, 5);
            janelaEE.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        } 
    }//GEN-LAST:event_tophatAberActionPerformed

    private void tophatFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tophatFechaActionPerformed
        // TODO add your handling code here:
        JFrame F = new JFrame();
        if(Img_carregada){
            ElementoEstruturante janelaEE = new ElementoEstruturante(this, 6);
            janelaEE.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(F, "Nenhuma imagem foi carregada!");
        } 
    }//GEN-LAST:event_tophatFechaActionPerformed

    private void inverterImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inverterImagemActionPerformed
        // TODO add your handling code here:
        
        BufferedImage nova_imagem = Morfologia.copyImage(getSelectedImg());
        int pixel;
        for(int i=0;i < nova_imagem.getWidth(); i++){
            for(int j = 0; j < nova_imagem.getHeight(); j++){
                pixel = (int) new Color(nova_imagem.getRGB(i,j)).getBlue()*(-1) + 255;
                nova_imagem.setRGB(i,j,new Color(pixel,pixel,pixel).getRGB());
            }
        }
//        String nameWithoutExtension = getSelectedImgName().replaceFirst("\\.[^.]+$", "");
        openInternalImg(nova_imagem,  getSelectedImgName(), "_invertida");
        
    }//GEN-LAST:event_inverterImagemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Tela_Aplicacao_Lote_Morfologia telaEmLote = new Tela_Aplicacao_Lote_Morfologia();
        telaEmLote.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void reconstrucaoRapidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reconstrucaoRapidaActionPerformed
        // TODO add your handling code here:
        Tela_Reconstrucao reconstrucao = new Tela_Reconstrucao(this, 1,jDesktopPane1.getAllFrames());
        reconstrucao.setVisible(true);
    }//GEN-LAST:event_reconstrucaoRapidaActionPerformed

    private void recostrucaoDualRapidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recostrucaoDualRapidaActionPerformed
        // TODO add your handling code here:
        Tela_Reconstrucao reconstrucao = new Tela_Reconstrucao(this, 2, jDesktopPane1.getAllFrames());
        reconstrucao.setVisible(true);
    }//GEN-LAST:event_recostrucaoDualRapidaActionPerformed

    private void bordaCinzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bordaCinzaActionPerformed
        // TODO add your handling code here:
        BufferedImage nova_imagem = Morfologia.copyImage(getSelectedImg());
        int pixel;
        for(int i=1;i < nova_imagem.getWidth()-1; i++){
            for(int j = 1; j < nova_imagem.getHeight()-1; j++){
                nova_imagem.setRGB(i,j,new Color(0,0,0).getRGB());
            }
        }
//        String nameWithoutExtension = getSelectedImgName().replaceFirst("\\.[^.]+$", "");
        openInternalImg(nova_imagem, getSelectedImgName(), "_borda");
    }//GEN-LAST:event_bordaCinzaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("FlatLaf".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Tela_Principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Tela_Principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Tela_Principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Tela_Principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal_().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Aplicar_FuzzyHuang_Imagem_;
    private javax.swing.JMenuItem Aplicar_FuzzyHuang_Lote_;
    private javax.swing.JMenuItem Aplicar_Otsu_Imagem_;
    private javax.swing.JMenuItem Aplicar_Otsu_Lote_;
    private javax.swing.JMenu Binarizacao_Fuzzy_Huang_;
    private javax.swing.JMenu Binarizacao_Otsu_;
    private javax.swing.JMenuItem Carregar_Imagem_;
    private javax.swing.JMenuItem Erosao;
    private javax.swing.JMenu Menu_Arquivo_;
    private javax.swing.JMenu Menu_Outros_;
    private javax.swing.JMenu Menu_Segmentacao_;
    private javax.swing.JMenuBar Menus;
    private javax.swing.JMenuItem Sair_;
    private javax.swing.JMenuItem Salvar_;
    private javax.swing.JMenuItem Sobre_;
    private javax.swing.JLabel Tela_;
    private javax.swing.JMenu Tophat;
    private javax.swing.JPopupMenu.Separator ___Separador_03;
    private javax.swing.JPopupMenu.Separator ___Separador_04;
    private javax.swing.JPopupMenu.Separator ___Separador_07;
    private javax.swing.JPopupMenu.Separator ___Separador_08;
    private javax.swing.JMenuItem abertura;
    private javax.swing.JMenuItem bordaCinza;
    private javax.swing.JMenuItem dilatacao;
    private javax.swing.JMenuItem fechamento;
    private javax.swing.JMenuItem inverterImagem;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenu menu_morfologia;
    private javax.swing.JMenuItem reconstrucaoRapida;
    private javax.swing.JMenuItem recostrucaoDualRapida;
    private javax.swing.JMenuItem tophatAber;
    private javax.swing.JMenuItem tophatFecha;
    // End of variables declaration//GEN-END:variables
}
