/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas.Deteccao_Pele;

import Processamento.Skin_Processor;
import Telas.Tela_Principal_;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;
import utils.Parametros_Deteccao_RGB;

/**
 *
 * @author Math
 */
public class Tela_Deteccao_Pele_RGB_Norm extends javax.swing.JFrame {
    
    boolean todosMarcados;
    
    private Tela_Principal_ telaPrincipal;
    
    Parametros_Deteccao_RGB params = new Parametros_Deteccao_RGB();

    /**
     * Creates new form Tela_Deteccao_Pele
     */
    public Tela_Deteccao_Pele_RGB_Norm(Tela_Principal_ telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        min_text = new javax.swing.JLabel();
        max_text = new javax.swing.JLabel();
        criterio_1 = new javax.swing.JCheckBox();
        criterio_2 = new javax.swing.JCheckBox();
        criterio_3 = new javax.swing.JCheckBox();
        criterio1_min_value = new javax.swing.JTextField();
        criterio1_max_value = new javax.swing.JTextField();
        criterio2_min_value = new javax.swing.JTextField();
        criterio2_max_value = new javax.swing.JTextField();
        criterio3_min_value = new javax.swing.JTextField();
        criterio3_max_value = new javax.swing.JTextField();
        aplicar_button = new javax.swing.JButton();
        todos_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Interface de Detecção de Pele - RGB Normalizado");

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setLabelFor(title);
        title.setText("RGB Normalizado");
        title.setAlignmentX(0.5F);
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        title.setName("title"); // NOI18N

        min_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        min_text.setText("Min");

        max_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        max_text.setText("Max");

        criterio_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        criterio_1.setText("<html><b>Critério 1:</b> r / g</html>");
        criterio_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterio_1ActionPerformed(evt);
            }
        });

        criterio_2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        criterio_2.setText("<html><b>Critério 2:</b> (r × b) / (r + g + b)²</html>");
        criterio_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterio_2ActionPerformed(evt);
            }
        });

        criterio_3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        criterio_3.setText("<html><b>Critério 3:</b> (r × g) / (r + g + b)²</html>");
        criterio_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterio_3ActionPerformed(evt);
            }
        });

        criterio1_min_value.setColumns(5);
        criterio1_min_value.setText("1.185");
        criterio1_min_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterio1_min_valueMouseClicked(evt);
            }
        });
        criterio1_min_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterio1_min_valueActionPerformed(evt);
            }
        });

        criterio1_max_value.setColumns(5);
        criterio1_max_value.setText("10");
        criterio1_max_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterio1_max_valueMouseClicked(evt);
            }
        });
        criterio1_max_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterio1_max_valueActionPerformed(evt);
            }
        });

        criterio2_min_value.setColumns(5);
        criterio2_min_value.setText("0.107");
        criterio2_min_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterio2_min_valueMouseClicked(evt);
            }
        });
        criterio2_min_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterio2_min_valueActionPerformed(evt);
            }
        });

        criterio2_max_value.setColumns(5);
        criterio2_max_value.setText("0.25");
        criterio2_max_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterio2_max_valueMouseClicked(evt);
            }
        });
        criterio2_max_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterio2_max_valueActionPerformed(evt);
            }
        });

        criterio3_min_value.setColumns(5);
        criterio3_min_value.setText("0.112");
        criterio3_min_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterio3_min_valueMouseClicked(evt);
            }
        });
        criterio3_min_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterio3_min_valueActionPerformed(evt);
            }
        });

        criterio3_max_value.setColumns(5);
        criterio3_max_value.setText("0.25");
        criterio3_max_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterio3_max_valueMouseClicked(evt);
            }
        });
        criterio3_max_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterio3_max_valueActionPerformed(evt);
            }
        });

        aplicar_button.setText("Aplicar");
        aplicar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicar_buttonActionPerformed(evt);
            }
        });

        todos_button.setText("Todos");
        todos_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todos_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(criterio_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterio_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterio_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(min_text)
                            .addComponent(criterio1_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterio2_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterio3_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(todos_button))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(max_text)
                    .addComponent(criterio1_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterio2_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterio3_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aplicar_button))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(min_text)
                    .addComponent(max_text))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterio_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterio1_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterio1_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterio_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterio2_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterio2_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterio_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterio3_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterio3_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(todos_button)
                    .addComponent(aplicar_button))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criterio_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterio_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterio_1ActionPerformed

    private void criterio_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterio_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterio_2ActionPerformed

    private void criterio_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterio_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterio_3ActionPerformed

    private void criterio1_max_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterio1_max_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterio1_max_valueActionPerformed

    private void criterio1_min_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterio1_min_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterio1_min_valueActionPerformed

    private void criterio2_min_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterio2_min_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterio2_min_valueActionPerformed

    private void criterio2_max_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterio2_max_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterio2_max_valueActionPerformed

    private void criterio3_min_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterio3_min_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterio3_min_valueActionPerformed

    private void criterio3_max_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterio3_max_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterio3_max_valueActionPerformed

    private void todos_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todos_buttonActionPerformed
        // TODO add your handling code here:
        todosMarcados = criterio_1.isSelected() && criterio_2.isSelected() && criterio_3.isSelected();
        
        criterio_1.setSelected(!todosMarcados);        
        criterio_2.setSelected(!todosMarcados);
        criterio_3.setSelected(!todosMarcados);
    }//GEN-LAST:event_todos_buttonActionPerformed

    private void aplicar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicar_buttonActionPerformed
        // TODO add your handling code here:
    
        params.usarCriterio1 = criterio_1.isSelected();
        params.usarCriterio2 = criterio_2.isSelected();
        params.usarCriterio3 = criterio_3.isSelected();
        
        try {
            if(params.usarCriterio1){
                params.criterio1Min = Double.parseDouble(criterio1_min_value.getText());
                params.criterio1Max = Double.parseDouble(criterio1_max_value.getText());
            }
            if(params.usarCriterio2){
                params.criterio2Min = Double.parseDouble(criterio2_min_value.getText());
                params.criterio2Max = Double.parseDouble(criterio2_max_value.getText());
            }
            if(params.usarCriterio3){
                params.criterio3Min = Double.parseDouble(criterio3_min_value.getText());
                params.criterio3Max = Double.parseDouble(criterio3_max_value.getText());
            }
                        
            BufferedImage img = telaPrincipal.getSelectedImg();
            BufferedImage processada = Skin_Processor.RGB_Norm(img, params);
            
            telaPrincipal.openInternalImg(processada, telaPrincipal.getSelectedImgName(), "_RGB");
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos numéricos corretamente.");
        }
    }//GEN-LAST:event_aplicar_buttonActionPerformed

    private void criterio1_min_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterio1_min_valueMouseClicked
        // TODO add your handling code here:
        criterio_1.setSelected(true);
    }//GEN-LAST:event_criterio1_min_valueMouseClicked

    private void criterio1_max_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterio1_max_valueMouseClicked
        // TODO add your handling code here:
        criterio_1.setSelected(true);
    }//GEN-LAST:event_criterio1_max_valueMouseClicked

    private void criterio2_min_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterio2_min_valueMouseClicked
        // TODO add your handling code here:
        criterio_2.setSelected(true);
    }//GEN-LAST:event_criterio2_min_valueMouseClicked

    private void criterio2_max_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterio2_max_valueMouseClicked
        // TODO add your handling code here:
        criterio_2.setSelected(true);
    }//GEN-LAST:event_criterio2_max_valueMouseClicked

    private void criterio3_min_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterio3_min_valueMouseClicked
        // TODO add your handling code here:
        criterio_3.setSelected(true);
    }//GEN-LAST:event_criterio3_min_valueMouseClicked

    private void criterio3_max_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterio3_max_valueMouseClicked
        // TODO add your handling code here:
        criterio_3.setSelected(true);
    }//GEN-LAST:event_criterio3_max_valueMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicar_button;
    private javax.swing.JTextField criterio1_max_value;
    private javax.swing.JTextField criterio1_min_value;
    private javax.swing.JTextField criterio2_max_value;
    private javax.swing.JTextField criterio2_min_value;
    private javax.swing.JTextField criterio3_max_value;
    private javax.swing.JTextField criterio3_min_value;
    private javax.swing.JCheckBox criterio_1;
    private javax.swing.JCheckBox criterio_2;
    private javax.swing.JCheckBox criterio_3;
    private javax.swing.JLabel max_text;
    private javax.swing.JLabel min_text;
    private javax.swing.JLabel title;
    private javax.swing.JButton todos_button;
    // End of variables declaration//GEN-END:variables
}
