package Telas.Deteccao_Pele;

import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import Processamento.Skin_Processor;
import Telas.util.Tela_Carregamento_;
import utils.Parametros_Deteccao_RGB;
import utils.Parametros_Deteccao_YCgCr;

/**
 * @author Matheus Silva Cruz - 2025/1
 */
public class Tela_Aplicacao_Lote_Deteccao_Pele extends javax.swing.JFrame {
    
    // Flag botão todos
     boolean todosMarcados;
    
    // Parâmetros dos filtros
    Parametros_Deteccao_RGB params = new Parametros_Deteccao_RGB();
    Parametros_Deteccao_YCgCr params2 = new Parametros_Deteccao_YCgCr();
    
    boolean aplicouRGB = false;
    boolean aplicouYCgCr = false;
    
    private String sufixo = "";
    
    // Atributos.
    private int Qnt_imagens;
    private boolean Finalizado = false;
    private int Qnt_imgs_processadas = 0;
    private File Pasta_origem, Pasta_destino;
    public  File Caminho = new File("/home/");
    private boolean Escolheu_origem = false, Escolheu_destino = false;

    
    /**
     * Creates new form TelaPostPasta
     */
    public Tela_Aplicacao_Lote_Deteccao_Pele() {   
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pasta_text = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Campo_Pasta_Origem_ = new javax.swing.JTextField();
        Selecionar_Pasta_Origem_ = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Campo_Pasta_Destino_ = new javax.swing.JTextField();
        Selecionar_Pasta_Destino_ = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Opcao_PNG_ = new javax.swing.JRadioButton();
        Opcao_JPG_ = new javax.swing.JRadioButton();
        Opcao_BMP_ = new javax.swing.JRadioButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        rgb_text = new javax.swing.JLabel();
        min_text = new javax.swing.JLabel();
        max_text = new javax.swing.JLabel();
        criterioRGB_1 = new javax.swing.JCheckBox();
        criterioRGB_2 = new javax.swing.JCheckBox();
        criterioRGB_3 = new javax.swing.JCheckBox();
        criterioRGB1_min_value = new javax.swing.JTextField();
        criterioRGB1_max_value = new javax.swing.JTextField();
        criterioRGB2_min_value = new javax.swing.JTextField();
        criterioRGB2_max_value = new javax.swing.JTextField();
        criterioRGB3_min_value = new javax.swing.JTextField();
        criterioRGB3_max_value = new javax.swing.JTextField();
        ycgcb_text = new javax.swing.JLabel();
        min_text1 = new javax.swing.JLabel();
        max_text1 = new javax.swing.JLabel();
        criterioYCgCr_1 = new javax.swing.JCheckBox();
        criterioYCgCr_2 = new javax.swing.JCheckBox();
        criterioYCgCr1_min_value = new javax.swing.JTextField();
        criterioYCgCr1_max_value = new javax.swing.JTextField();
        criterioYCgCr2_min_value = new javax.swing.JTextField();
        criterioYCgCr2_max_value = new javax.swing.JTextField();
        todos_button = new javax.swing.JButton();
        Cancelar_ = new javax.swing.JButton();
        Aplicar_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplicação em Lote");
        setFocusCycleRoot(false);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplicação em Lote");
        jLabel1.setToolTipText("");
        jLabel1.setName(""); // NOI18N

        jPanel1.setPreferredSize(new java.awt.Dimension(550, 550));

        pasta_text.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        pasta_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pasta_text.setText("PASTA");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("        Selecione uma pasta com arquivos de imagem:");

        Campo_Pasta_Origem_.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Campo_Pasta_Origem_.setText("Selecione uma pasta de origem...");
        Campo_Pasta_Origem_.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Campo_Pasta_Origem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_Pasta_Origem_ActionPerformed(evt);
            }
        });

        Selecionar_Pasta_Origem_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Selecionar_Pasta_Origem_.setText("Selecionar...");
        Selecionar_Pasta_Origem_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selecionar_Pasta_Origem_ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Selecione uma pasta para salvar as imagens processadas:              ");

        Campo_Pasta_Destino_.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Campo_Pasta_Destino_.setText("Selecione uma pasta de destino...");
        Campo_Pasta_Destino_.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Selecionar_Pasta_Destino_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Selecionar_Pasta_Destino_.setText("Selecionar...");
        Selecionar_Pasta_Destino_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selecionar_Pasta_Destino_ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Selecione a(s) extensão(ões) das imagens que devem ser  processadas:");

        Opcao_PNG_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Opcao_PNG_.setSelected(true);
        Opcao_PNG_.setText("PNG");

        Opcao_JPG_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Opcao_JPG_.setText("JPEG/JPG");

        Opcao_BMP_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Opcao_BMP_.setText("BMP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pasta_text, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Campo_Pasta_Destino_, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Selecionar_Pasta_Destino_, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(Opcao_PNG_)
                                .addGap(62, 62, 62)
                                .addComponent(Opcao_JPG_)
                                .addGap(18, 18, 18)
                                .addComponent(Opcao_BMP_))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(Campo_Pasta_Origem_, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Selecionar_Pasta_Origem_, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pasta_text)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Campo_Pasta_Origem_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Selecionar_Pasta_Origem_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Campo_Pasta_Destino_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Selecionar_Pasta_Destino_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opcao_PNG_)
                    .addComponent(Opcao_JPG_)
                    .addComponent(Opcao_BMP_))
                .addGap(56, 56, 56))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel2.setPreferredSize(new java.awt.Dimension(550, 550));

        rgb_text.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        rgb_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rgb_text.setText("Filtro RGB");

        min_text.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        min_text.setText("Min");

        max_text.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        max_text.setText("Max");

        criterioRGB_1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        criterioRGB_1.setText("<html><b>Critério 1:</b> r / g</html>");
        criterioRGB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioRGB_1ActionPerformed(evt);
            }
        });

        criterioRGB_2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        criterioRGB_2.setText("<html><b>Critério 2:</b> (r × b) / (r + g + b)²</html>");

        criterioRGB_3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        criterioRGB_3.setText("<html><b>Critério 3:</b> (r × g) / (r + g + b)²</html>");

        criterioRGB1_min_value.setColumns(5);
        criterioRGB1_min_value.setText("1.185");
        criterioRGB1_min_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioRGB1_min_valueMouseClicked(evt);
            }
        });

        criterioRGB1_max_value.setColumns(5);
        criterioRGB1_max_value.setText("10");
        criterioRGB1_max_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioRGB1_max_valueMouseClicked(evt);
            }
        });

        criterioRGB2_min_value.setColumns(5);
        criterioRGB2_min_value.setText("0.107");
        criterioRGB2_min_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioRGB2_min_valueMouseClicked(evt);
            }
        });

        criterioRGB2_max_value.setColumns(5);
        criterioRGB2_max_value.setText("0.25");
        criterioRGB2_max_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioRGB2_max_valueMouseClicked(evt);
            }
        });

        criterioRGB3_min_value.setColumns(5);
        criterioRGB3_min_value.setText("0.112");
        criterioRGB3_min_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioRGB3_min_valueMouseClicked(evt);
            }
        });

        criterioRGB3_max_value.setColumns(5);
        criterioRGB3_max_value.setText("0.25");
        criterioRGB3_max_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioRGB3_max_valueMouseClicked(evt);
            }
        });

        ycgcb_text.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        ycgcb_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ycgcb_text.setText("Filtro YCgCr");

        min_text1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        min_text1.setText("Min");

        max_text1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        max_text1.setText("Max");

        criterioYCgCr_1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        criterioYCgCr_1.setText("<html><b>Critério 1:</b> Cg</html>");

        criterioYCgCr_2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        criterioYCgCr_2.setText("<html><b>Critério 2:</b> Cr</html>");

        criterioYCgCr1_min_value.setColumns(5);
        criterioYCgCr1_min_value.setText("76");
        criterioYCgCr1_min_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioYCgCr1_min_valueMouseClicked(evt);
            }
        });

        criterioYCgCr1_max_value.setColumns(5);
        criterioYCgCr1_max_value.setText("125");
        criterioYCgCr1_max_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioYCgCr1_max_valueMouseClicked(evt);
            }
        });
        criterioYCgCr1_max_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioYCgCr1_max_valueActionPerformed(evt);
            }
        });

        criterioYCgCr2_min_value.setColumns(5);
        criterioYCgCr2_min_value.setText("136");
        criterioYCgCr2_min_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioYCgCr2_min_valueMouseClicked(evt);
            }
        });
        criterioYCgCr2_min_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioYCgCr2_min_valueActionPerformed(evt);
            }
        });

        criterioYCgCr2_max_value.setColumns(5);
        criterioYCgCr2_max_value.setText("202");
        criterioYCgCr2_max_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioYCgCr2_max_valueMouseClicked(evt);
            }
        });

        todos_button.setText("Todos");
        todos_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todos_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rgb_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ycgcb_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(criterioYCgCr_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(criterioYCgCr_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(criterioRGB_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(criterioRGB_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(criterioRGB_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(min_text1)
                                    .addComponent(criterioYCgCr1_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(criterioYCgCr2_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(criterioRGB3_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(criterioRGB2_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(criterioRGB1_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(min_text))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(max_text)
                                        .addComponent(criterioRGB1_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(criterioRGB2_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(criterioRGB3_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(max_text1)
                                        .addComponent(criterioYCgCr1_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(criterioYCgCr2_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(todos_button)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rgb_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(min_text)
                    .addComponent(max_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(criterioRGB_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioRGB1_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioRGB1_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(criterioRGB_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioRGB2_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioRGB2_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(criterioRGB_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioRGB3_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioRGB3_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(ycgcb_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(max_text1)
                    .addComponent(min_text1))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(criterioYCgCr_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioYCgCr1_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioYCgCr1_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(criterioYCgCr_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioYCgCr2_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioYCgCr2_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(todos_button)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Cancelar_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Cancelar_.setText("Cancelar");
        Cancelar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_ActionPerformed(evt);
            }
        });

        Aplicar_.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Aplicar_.setText("Aplicar");
        Aplicar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aplicar_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(Cancelar_, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Aplicar_, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                        .addComponent(jSeparator1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Cancelar_)
                    .addComponent(Aplicar_))
                .addGap(17, 17, 17))
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("Aplicação em Lote");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /*  Metodo para selecionar uma pasta com arquivos de imagem.    */
    private void Selecionar_Pasta_Origem_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selecionar_Pasta_Origem_ActionPerformed

        try{
           
            // Configura e abre uma janela de dialogo.
            JFileChooser Fs = new JFileChooser(Caminho);
            Fs.setDialogTitle("Selecione uma pasta com arquivos de imagem...");
            Fs.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            Fs.setAcceptAllFileFilterUsed(false);
            int Retorno = Fs.showOpenDialog(null);
            
            // Seleciona a pasta.
            if (Retorno == JFileChooser.APPROVE_OPTION){
                
                Campo_Pasta_Origem_.setText(Fs.getSelectedFile().getPath());
                Pasta_origem    = Fs.getSelectedFile();
                Caminho         = Fs.getCurrentDirectory();
                Escolheu_origem = true;
            }           
        } catch(NullPointerException ex){
            Logger.getLogger(Tela_Aplicacao_Lote_Deteccao_Pele.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_Selecionar_Pasta_Origem_ActionPerformed

    private BufferedImage aplicarFiltrosDeteccao(BufferedImage imagemOriginal) {
    BufferedImage resultado = imagemOriginal;
    
    if (aplicouRGB) {
        resultado = Skin_Processor.RGB_Norm(resultado, params);
    }

    if (aplicouYCgCr) {
        resultado = Skin_Processor.YCgCr(resultado, params2);
    }

    return resultado;
}

    
    /*  Metodo para aplicar algoritmos em um lote de imagens.   */
    private void Aplicar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aplicar_ActionPerformed

        
        // RGB Criterios
        params.usarCriterio1 = criterioRGB_1.isSelected();
        params.usarCriterio2 = criterioRGB_2.isSelected();
        params.usarCriterio3 = criterioRGB_3.isSelected();

        // YCgCr Criterios
        params2.usarCriterio1 = criterioYCgCr_1.isSelected();
        params2.usarCriterio2 = criterioYCgCr_2.isSelected();

        aplicouRGB = params.usarCriterio1 || params.usarCriterio2 || params.usarCriterio3;
        aplicouYCgCr = params2.usarCriterio1 || params2.usarCriterio2;
        
        if(Escolheu_origem && Escolheu_destino && (aplicouRGB || aplicouYCgCr)){

            Finalizado  = false;
            Qnt_imagens = 0;
            Qnt_imgs_processadas = 0;

            // Calcula a quantidade de arquivos de imagem na pasta de origem.
            for(File Arquivos: Pasta_origem.listFiles()){

                if((Opcao_PNG_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".png"))||
                   (Opcao_JPG_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".jpg")) ||
                   (Opcao_JPG_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".jpeg")) ||
                   (Opcao_BMP_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".bmp")))
                {
                    Qnt_imagens++;
                }                               
            }
            
            

            try {
                // Parâmetros RGB
                params.criterio1Min = Double.parseDouble(criterioRGB1_min_value.getText());
                params.criterio1Max = Double.parseDouble(criterioRGB1_max_value.getText());
                params.criterio2Min = Double.parseDouble(criterioRGB2_min_value.getText());
                params.criterio2Max = Double.parseDouble(criterioRGB2_max_value.getText());
                params.criterio3Min = Double.parseDouble(criterioRGB3_min_value.getText());
                params.criterio3Max = Double.parseDouble(criterioRGB3_max_value.getText());

                // Parâmetros YCgCr
                params2.criterio1Min = Double.parseDouble(criterioYCgCr1_min_value.getText());
                params2.criterio1Max = Double.parseDouble(criterioYCgCr1_max_value.getText());
                params2.criterio2Min = Double.parseDouble(criterioYCgCr2_min_value.getText());
                params2.criterio2Max = Double.parseDouble(criterioYCgCr2_max_value.getText());

                // Define sufixo do nome
                if (aplicouRGB && aplicouYCgCr) sufixo = "_rgbYCgCr";
                else if (aplicouRGB) sufixo = "_rgb";
                else if (aplicouYCgCr) sufixo = "_YCgCr";

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos numéricos corretamente.");
            }
            
            
            // Cria uma Thread.
            Thread T1 = new Thread(){
                
                @Override
                
                public void run(){
                    
                    for(File Arquivos: Pasta_origem.listFiles()){
                        
                        // Identifica os arquivos de imagem, com a extensao selecionada, dentro da pasta.
                        if((Opcao_PNG_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".png"))||
                           (Opcao_JPG_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".jpg")) ||
                           (Opcao_JPG_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".jpeg")) ||
                           (Opcao_BMP_.isSelected() && Arquivos.getName().toLowerCase().endsWith(".bmp")))
                        {
                            
                            try {
                                
                                // Pega uma imagem.
                                BufferedImage Img_original   = ImageIO.read(Arquivos);
                                BufferedImage Img_Processada = aplicarFiltrosDeteccao(Img_original);
                                
                                // Salva a imagem processada.
                                File Fo = new File(Pasta_destino.getPath() +"/" +Arquivos.getName().substring(0, Arquivos.getName().length() - 4) +sufixo +".png");
                                ImageIO.write(Img_Processada, "png", Fo);
                                Qnt_imgs_processadas++;
                                
                            } catch (IOException ex) {
                                Logger.getLogger(Tela_Aplicacao_Lote_Deteccao_Pele.class.getName()).log(Level.SEVERE, null, ex);
                            }    
                        }                
                    }
                    
                    Finalizado = true;
                }
            };
            
            T1.start();   // Inicia a Thread.
            
            
            // Cria uma Thread.
            Thread T2 = new Thread(){
                
                @Override
                
                public void run(){
                    
                    // Exibe e executa uma janela de carregamento.
                    Tela_Carregamento_ Tc = new Tela_Carregamento_();
                    Tc.setVisible(true);
                    while(!Finalizado){
                        
                        Tc.Atualizar_Progresso_(Qnt_imgs_processadas, Qnt_imagens);
                    }
                    Tc.dispose();
                    
                    if(Qnt_imgs_processadas > 0 ){
                        
                        // Exibe uma mensagem confirmando o fim da aplicacao do algoritmo.
                        JOptionPane.showMessageDialog(rootPane, Qnt_imgs_processadas +" imagens foram processadas com sucesso!", "Aplicação realizada!", JOptionPane.INFORMATION_MESSAGE);                
                        Desktop desktop = Desktop.getDesktop();
                        
                        try {
                            desktop.open(Pasta_destino);    // Abre a pasta de destino.
                        }catch (IOException ex) {
                            Logger.getLogger(Tela_Aplicacao_Lote_Deteccao_Pele.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Não foram encontradas imagens, com as extensões especificadas, na pasta de origem!");            
                    }
                }
            };
            
            T2.start();   // Inicia a Thread.
            
            
        }else if(!Escolheu_origem){
            JOptionPane.showMessageDialog(null, "A pasta de origem não foi especificada!");            
        }else if(!Escolheu_destino){
            JOptionPane.showMessageDialog(null, "A pasta de destino não foi especificada!");
        }else if (!aplicouRGB && !aplicouYCgCr) {
            JOptionPane.showMessageDialog(null, "Nenhum critério foi selecionado!");
        }
    }//GEN-LAST:event_Aplicar_ActionPerformed

    
    /*  Metodo para cancelar a aplicacao de algum
        algoritmo em um lote de imagens.    */
    private void Cancelar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_ActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cancelar_ActionPerformed

    
    /*  Metodo para selecionar uma pasta de destino para as imagens processadas.    */
    private void Selecionar_Pasta_Destino_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selecionar_Pasta_Destino_ActionPerformed

        try{
            
            // Configura e abre uma janela de dialogo.
            JFileChooser Fs = new JFileChooser(Caminho);
            Fs.setDialogTitle("Selecione uma pasta para as imagens processadas...");
            Fs.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            Fs.setAcceptAllFileFilterUsed(false);
            int Retorno = Fs.showOpenDialog(null);
            
            // Seleciona a pasta.
            if (Retorno == JFileChooser.APPROVE_OPTION){
            
                Campo_Pasta_Destino_.setText(Fs.getSelectedFile().getPath());
                Pasta_destino = Fs.getSelectedFile();
                Caminho       = Fs.getCurrentDirectory();
                Escolheu_destino = true;
            }
        } catch(NullPointerException ex){
            Logger.getLogger(Tela_Aplicacao_Lote_Deteccao_Pele.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Selecionar_Pasta_Destino_ActionPerformed

    private void criterioYCgCr2_min_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioYCgCr2_min_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioYCgCr2_min_valueActionPerformed

    private void criterioYCgCr1_max_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioYCgCr1_max_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioYCgCr1_max_valueActionPerformed

    private void Campo_Pasta_Origem_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_Pasta_Origem_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_Pasta_Origem_ActionPerformed

    private void criterioRGB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioRGB_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioRGB_1ActionPerformed

    private void todos_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todos_buttonActionPerformed
        // TODO add your handling code here:
        todosMarcados = criterioRGB_1.isSelected()
                    && criterioRGB_2.isSelected()
                    && criterioRGB_3.isSelected()
                    && criterioYCgCr_1.isSelected()
                    && criterioYCgCr_2.isSelected();

        criterioRGB_1.setSelected(!todosMarcados);
        criterioRGB_2.setSelected(!todosMarcados);
        criterioRGB_3.setSelected(!todosMarcados);
        criterioYCgCr_1.setSelected(!todosMarcados);
        criterioYCgCr_2.setSelected(!todosMarcados);
    }//GEN-LAST:event_todos_buttonActionPerformed

    private void criterioRGB1_min_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioRGB1_min_valueMouseClicked
        // TODO add your handling code here:
        criterioRGB_1.setSelected(true);
    }//GEN-LAST:event_criterioRGB1_min_valueMouseClicked

    private void criterioRGB1_max_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioRGB1_max_valueMouseClicked
        // TODO add your handling code here:
        criterioRGB_1.setSelected(true);
    }//GEN-LAST:event_criterioRGB1_max_valueMouseClicked

    private void criterioRGB2_min_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioRGB2_min_valueMouseClicked
        // TODO add your handling code here:
        criterioRGB_2.setSelected(true);
    }//GEN-LAST:event_criterioRGB2_min_valueMouseClicked

    private void criterioRGB2_max_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioRGB2_max_valueMouseClicked
        // TODO add your handling code here:
        criterioRGB_2.setSelected(true);
    }//GEN-LAST:event_criterioRGB2_max_valueMouseClicked

    private void criterioRGB3_min_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioRGB3_min_valueMouseClicked
        // TODO add your handling code here:
        criterioRGB_3.setSelected(true);
    }//GEN-LAST:event_criterioRGB3_min_valueMouseClicked

    private void criterioRGB3_max_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioRGB3_max_valueMouseClicked
        // TODO add your handling code here:
        criterioRGB_3.setSelected(true);
    }//GEN-LAST:event_criterioRGB3_max_valueMouseClicked

    private void criterioYCgCr1_min_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioYCgCr1_min_valueMouseClicked
        // TODO add your handling code here:
        criterioYCgCr_1.setSelected(true);
    }//GEN-LAST:event_criterioYCgCr1_min_valueMouseClicked

    private void criterioYCgCr1_max_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioYCgCr1_max_valueMouseClicked
        // TODO add your handling code here:
        criterioYCgCr_1.setSelected(true);
    }//GEN-LAST:event_criterioYCgCr1_max_valueMouseClicked

    private void criterioYCgCr2_min_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioYCgCr2_min_valueMouseClicked
        // TODO add your handling code here:
        criterioYCgCr_2.setSelected(true);
    }//GEN-LAST:event_criterioYCgCr2_min_valueMouseClicked

    private void criterioYCgCr2_max_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioYCgCr2_max_valueMouseClicked
        // TODO add your handling code here:
        criterioYCgCr_2.setSelected(true);
    }//GEN-LAST:event_criterioYCgCr2_max_valueMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Aplicacao_Lote_Deteccao_Pele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Aplicacao_Lote_Deteccao_Pele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Aplicacao_Lote_Deteccao_Pele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Aplicacao_Lote_Deteccao_Pele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Aplicacao_Lote_Deteccao_Pele().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aplicar_;
    private javax.swing.JTextField Campo_Pasta_Destino_;
    private javax.swing.JTextField Campo_Pasta_Origem_;
    private javax.swing.JButton Cancelar_;
    private javax.swing.JRadioButton Opcao_BMP_;
    private javax.swing.JRadioButton Opcao_JPG_;
    private javax.swing.JRadioButton Opcao_PNG_;
    private javax.swing.JButton Selecionar_Pasta_Destino_;
    private javax.swing.JButton Selecionar_Pasta_Origem_;
    private javax.swing.JTextField criterioRGB1_max_value;
    private javax.swing.JTextField criterioRGB1_min_value;
    private javax.swing.JTextField criterioRGB2_max_value;
    private javax.swing.JTextField criterioRGB2_min_value;
    private javax.swing.JTextField criterioRGB3_max_value;
    private javax.swing.JTextField criterioRGB3_min_value;
    private javax.swing.JCheckBox criterioRGB_1;
    private javax.swing.JCheckBox criterioRGB_2;
    private javax.swing.JCheckBox criterioRGB_3;
    private javax.swing.JTextField criterioYCgCr1_max_value;
    private javax.swing.JTextField criterioYCgCr1_min_value;
    private javax.swing.JTextField criterioYCgCr2_max_value;
    private javax.swing.JTextField criterioYCgCr2_min_value;
    private javax.swing.JCheckBox criterioYCgCr_1;
    private javax.swing.JCheckBox criterioYCgCr_2;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel max_text;
    private javax.swing.JLabel max_text1;
    private javax.swing.JLabel min_text;
    private javax.swing.JLabel min_text1;
    private javax.swing.JLabel pasta_text;
    private javax.swing.JLabel rgb_text;
    private javax.swing.JButton todos_button;
    private javax.swing.JLabel ycgcb_text;
    // End of variables declaration//GEN-END:variables
}
