/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas.Deteccao_Pele;

import Processamento.Skin_Processor;
import Telas.Tela_Principal_;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;
import utils.Parametros_Deteccao_RGB;
import utils.Parametros_Deteccao_YCgCr;

/**
 *
 * @author Math
 */
public class Tela_Deteccao_Pele_Comb extends javax.swing.JFrame {
    
    boolean todosMarcados;
    
    private Tela_Principal_ telaPrincipal;
    
    
    Parametros_Deteccao_RGB params = new Parametros_Deteccao_RGB();
    Parametros_Deteccao_YCgCr params2 = new Parametros_Deteccao_YCgCr();
    

    /**
     * Creates new form Tela_Deteccao_Comb
     */
    public Tela_Deteccao_Pele_Comb(Tela_Principal_ telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        min_text1 = new javax.swing.JLabel();
        max_text1 = new javax.swing.JLabel();
        criterioRGB_1 = new javax.swing.JCheckBox();
        criterioRGB_2 = new javax.swing.JCheckBox();
        criterioRGB_3 = new javax.swing.JCheckBox();
        criterioRGB1_min_value = new javax.swing.JTextField();
        criterioRGB1_max_value = new javax.swing.JTextField();
        criterioRGB2_min_value = new javax.swing.JTextField();
        criterioRGB2_max_value = new javax.swing.JTextField();
        criterioRGB3_min_value = new javax.swing.JTextField();
        criterioRGB3_max_value = new javax.swing.JTextField();
        min_text = new javax.swing.JLabel();
        max_text = new javax.swing.JLabel();
        criterioYCgCr_1 = new javax.swing.JCheckBox();
        criterioYCgCr_2 = new javax.swing.JCheckBox();
        criterioYCgCr1_min_value = new javax.swing.JTextField();
        criterioYCgCr1_max_value = new javax.swing.JTextField();
        criterioYCgCr2_min_value = new javax.swing.JTextField();
        criterioYCgCr2_max_value = new javax.swing.JTextField();
        aplicar_button = new javax.swing.JButton();
        todos_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Combinação RGB Normalizado com YCgCr");
        title.setAlignmentX(0.5F);
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        title.setName("title"); // NOI18N

        min_text1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        min_text1.setText("Min");

        max_text1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        max_text1.setText("Max");

        criterioRGB_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        criterioRGB_1.setText("<html><b>Critério 1:</b> r / g</html>");
        criterioRGB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioRGB_1ActionPerformed(evt);
            }
        });

        criterioRGB_2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        criterioRGB_2.setText("<html><b>Critério 2:</b> (r × b) / (r + g + b)²</html>");
        criterioRGB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioRGB_2ActionPerformed(evt);
            }
        });

        criterioRGB_3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        criterioRGB_3.setText("<html><b>Critério 3:</b> (r × g) / (r + g + b)²</html>");
        criterioRGB_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioRGB_3ActionPerformed(evt);
            }
        });

        criterioRGB1_min_value.setColumns(5);
        criterioRGB1_min_value.setText("1.185");
        criterioRGB1_min_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioRGB1_min_valueMouseClicked(evt);
            }
        });
        criterioRGB1_min_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioRGB1_min_valueActionPerformed(evt);
            }
        });

        criterioRGB1_max_value.setColumns(5);
        criterioRGB1_max_value.setText("10");
        criterioRGB1_max_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioRGB1_max_valueMouseClicked(evt);
            }
        });
        criterioRGB1_max_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioRGB1_max_valueActionPerformed(evt);
            }
        });

        criterioRGB2_min_value.setColumns(5);
        criterioRGB2_min_value.setText("0.107");
        criterioRGB2_min_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioRGB2_min_valueMouseClicked(evt);
            }
        });
        criterioRGB2_min_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioRGB2_min_valueActionPerformed(evt);
            }
        });

        criterioRGB2_max_value.setColumns(5);
        criterioRGB2_max_value.setText("0.25");
        criterioRGB2_max_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioRGB2_max_valueMouseClicked(evt);
            }
        });
        criterioRGB2_max_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioRGB2_max_valueActionPerformed(evt);
            }
        });

        criterioRGB3_min_value.setColumns(5);
        criterioRGB3_min_value.setText("0.112");
        criterioRGB3_min_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioRGB3_min_valueMouseClicked(evt);
            }
        });
        criterioRGB3_min_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioRGB3_min_valueActionPerformed(evt);
            }
        });

        criterioRGB3_max_value.setColumns(5);
        criterioRGB3_max_value.setText("0.25");
        criterioRGB3_max_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioRGB3_max_valueMouseClicked(evt);
            }
        });
        criterioRGB3_max_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioRGB3_max_valueActionPerformed(evt);
            }
        });

        min_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        min_text.setText("Min");

        max_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        max_text.setText("Max");

        criterioYCgCr_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        criterioYCgCr_1.setText("<html><b>Critério 1:</b> Cg</html>");
        criterioYCgCr_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioYCgCr_1ActionPerformed(evt);
            }
        });

        criterioYCgCr_2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        criterioYCgCr_2.setText("<html><b>Critério 2:</b> Cr</html>");
        criterioYCgCr_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioYCgCr_2ActionPerformed(evt);
            }
        });

        criterioYCgCr1_min_value.setColumns(5);
        criterioYCgCr1_min_value.setText("76");
        criterioYCgCr1_min_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioYCgCr1_min_valueMouseClicked(evt);
            }
        });
        criterioYCgCr1_min_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioYCgCr1_min_valueActionPerformed(evt);
            }
        });

        criterioYCgCr1_max_value.setColumns(5);
        criterioYCgCr1_max_value.setText("125");
        criterioYCgCr1_max_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioYCgCr1_max_valueMouseClicked(evt);
            }
        });
        criterioYCgCr1_max_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioYCgCr1_max_valueActionPerformed(evt);
            }
        });

        criterioYCgCr2_min_value.setColumns(5);
        criterioYCgCr2_min_value.setText("136");
        criterioYCgCr2_min_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioYCgCr2_min_valueMouseClicked(evt);
            }
        });
        criterioYCgCr2_min_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioYCgCr2_min_valueActionPerformed(evt);
            }
        });

        criterioYCgCr2_max_value.setColumns(5);
        criterioYCgCr2_max_value.setText("202");
        criterioYCgCr2_max_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criterioYCgCr2_max_valueMouseClicked(evt);
            }
        });
        criterioYCgCr2_max_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterioYCgCr2_max_valueActionPerformed(evt);
            }
        });

        aplicar_button.setText("Aplicar");
        aplicar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicar_buttonActionPerformed(evt);
            }
        });

        todos_button.setText("Todos");
        todos_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todos_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(criterioRGB_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterioRGB_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterioRGB_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterioYCgCr_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterioYCgCr_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(min_text1)
                            .addComponent(criterioRGB1_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterioRGB2_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterioRGB3_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(min_text)
                            .addComponent(criterioYCgCr1_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterioYCgCr2_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(max_text1)
                            .addComponent(criterioRGB1_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterioRGB2_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterioRGB3_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(max_text)
                            .addComponent(criterioYCgCr1_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criterioYCgCr2_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aplicar_button)))
                    .addComponent(todos_button))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(min_text1)
                    .addComponent(max_text1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterioRGB_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioRGB1_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioRGB1_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterioRGB_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioRGB2_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioRGB2_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterioRGB_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioRGB3_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioRGB3_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(min_text)
                    .addComponent(max_text))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterioYCgCr_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioYCgCr1_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioYCgCr1_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterioYCgCr_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioYCgCr2_max_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criterioYCgCr2_min_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(todos_button)
                    .addComponent(aplicar_button))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criterioYCgCr_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioYCgCr_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioYCgCr_1ActionPerformed

    private void criterioYCgCr_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioYCgCr_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioYCgCr_2ActionPerformed

    private void criterioYCgCr1_min_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioYCgCr1_min_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioYCgCr1_min_valueActionPerformed

    private void criterioYCgCr1_max_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioYCgCr1_max_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioYCgCr1_max_valueActionPerformed

    private void criterioYCgCr2_min_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioYCgCr2_min_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioYCgCr2_min_valueActionPerformed

    private void criterioYCgCr2_max_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioYCgCr2_max_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioYCgCr2_max_valueActionPerformed

private void aplicar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicar_buttonActionPerformed

    // RGB Criterios
    params.usarCriterio1 = criterioRGB_1.isSelected();
    params.usarCriterio2 = criterioRGB_2.isSelected();
    params.usarCriterio3 = criterioRGB_3.isSelected();

    // YCgCr Criterios
    params2.usarCriterio1 = criterioYCgCr_1.isSelected();
    params2.usarCriterio2 = criterioYCgCr_2.isSelected();

    try {
        // Parâmetros RGB
        params.criterio1Min = Double.parseDouble(criterioRGB1_min_value.getText());
        params.criterio1Max = Double.parseDouble(criterioRGB1_max_value.getText());
        params.criterio2Min = Double.parseDouble(criterioRGB2_min_value.getText());
        params.criterio2Max = Double.parseDouble(criterioRGB2_max_value.getText());
        params.criterio3Min = Double.parseDouble(criterioRGB3_min_value.getText());
        params.criterio3Max = Double.parseDouble(criterioRGB3_max_value.getText());

        // Parâmetros YCgCr
        params2.criterio1Min = Double.parseDouble(criterioYCgCr1_min_value.getText());
        params2.criterio1Max = Double.parseDouble(criterioYCgCr1_max_value.getText());
        params2.criterio2Min = Double.parseDouble(criterioYCgCr2_min_value.getText());
        params2.criterio2Max = Double.parseDouble(criterioYCgCr2_max_value.getText());

        BufferedImage img = telaPrincipal.getSelectedImg(); // original
        String nomeBase = telaPrincipal.getSelectedImgName();

        boolean aplicouRGB = params.usarCriterio1 || params.usarCriterio2 || params.usarCriterio3;
        boolean aplicouYCgCr = params2.usarCriterio1 || params2.usarCriterio2;

        if (!aplicouRGB && !aplicouYCgCr) {
            JOptionPane.showMessageDialog(null, "Nenhum critério foi selecionado.");
            return;
        }

        BufferedImage imgProcessada = img;

        if (aplicouRGB) {
            imgProcessada = Skin_Processor.RGB_Norm(imgProcessada, params);
        }

        if (aplicouYCgCr) {
            imgProcessada = Skin_Processor.YCgCr(imgProcessada, params2);
        }

        // Define sufixo do nome
        String sufixo = "";
        if (aplicouRGB && aplicouYCgCr) sufixo = "_RGB_YCgCr";
        else if (aplicouRGB) sufixo = "_RGB";
        else if (aplicouYCgCr) sufixo = "_YCgCr";

        // Abre nova janela com imagem processada
        telaPrincipal.openInternalImg(imgProcessada, nomeBase, sufixo);

        this.dispose();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Preencha todos os campos numéricos corretamente.");
    }
}

//GEN-LAST:event_aplicar_buttonActionPerformed

    private void todos_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todos_buttonActionPerformed
        // TODO add your handling code here:
        todosMarcados = criterioRGB_1.isSelected() 
                    && criterioRGB_2.isSelected() 
                    && criterioRGB_3.isSelected() 
                    && criterioYCgCr_1.isSelected() 
                    && criterioYCgCr_2.isSelected();

        criterioRGB_1.setSelected(!todosMarcados);        
        criterioRGB_2.setSelected(!todosMarcados);
        criterioRGB_3.setSelected(!todosMarcados);
        criterioYCgCr_1.setSelected(!todosMarcados);
        criterioYCgCr_2.setSelected(!todosMarcados);
    }//GEN-LAST:event_todos_buttonActionPerformed

    private void criterioRGB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioRGB_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioRGB_1ActionPerformed

    private void criterioRGB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioRGB_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioRGB_2ActionPerformed

    private void criterioRGB_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioRGB_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioRGB_3ActionPerformed

    private void criterioRGB1_min_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioRGB1_min_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioRGB1_min_valueActionPerformed

    private void criterioRGB1_max_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioRGB1_max_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioRGB1_max_valueActionPerformed

    private void criterioRGB2_min_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioRGB2_min_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioRGB2_min_valueActionPerformed

    private void criterioRGB2_max_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioRGB2_max_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioRGB2_max_valueActionPerformed

    private void criterioRGB3_min_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioRGB3_min_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioRGB3_min_valueActionPerformed

    private void criterioRGB3_max_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criterioRGB3_max_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criterioRGB3_max_valueActionPerformed

    private void criterioRGB1_min_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioRGB1_min_valueMouseClicked
        // TODO add your handling code here:
        criterioRGB_1.setSelected(true);
    }//GEN-LAST:event_criterioRGB1_min_valueMouseClicked

    private void criterioRGB1_max_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioRGB1_max_valueMouseClicked
        // TODO add your handling code here:
        criterioRGB_1.setSelected(true);
    }//GEN-LAST:event_criterioRGB1_max_valueMouseClicked

    private void criterioRGB2_min_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioRGB2_min_valueMouseClicked
        // TODO add your handling code here:
        criterioRGB_2.setSelected(true);
    }//GEN-LAST:event_criterioRGB2_min_valueMouseClicked

    private void criterioRGB2_max_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioRGB2_max_valueMouseClicked
        // TODO add your handling code here:
        criterioRGB_2.setSelected(true);
    }//GEN-LAST:event_criterioRGB2_max_valueMouseClicked

    private void criterioRGB3_min_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioRGB3_min_valueMouseClicked
        // TODO add your handling code here:
        criterioRGB_3.setSelected(true);
    }//GEN-LAST:event_criterioRGB3_min_valueMouseClicked

    private void criterioRGB3_max_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioRGB3_max_valueMouseClicked
        // TODO add your handling code here:
        criterioRGB_3.setSelected(true);
    }//GEN-LAST:event_criterioRGB3_max_valueMouseClicked

    private void criterioYCgCr1_min_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioYCgCr1_min_valueMouseClicked
        // TODO add your handling code here:
        criterioYCgCr_1.setSelected(true);
    }//GEN-LAST:event_criterioYCgCr1_min_valueMouseClicked

    private void criterioYCgCr1_max_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioYCgCr1_max_valueMouseClicked
        // TODO add your handling code here:
        criterioYCgCr_1.setSelected(true);
    }//GEN-LAST:event_criterioYCgCr1_max_valueMouseClicked

    private void criterioYCgCr2_min_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioYCgCr2_min_valueMouseClicked
        // TODO add your handling code here:
        criterioYCgCr_2.setSelected(true);
    }//GEN-LAST:event_criterioYCgCr2_min_valueMouseClicked

    private void criterioYCgCr2_max_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criterioYCgCr2_max_valueMouseClicked
        // TODO add your handling code here:
        criterioYCgCr_2.setSelected(true);
    }//GEN-LAST:event_criterioYCgCr2_max_valueMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicar_button;
    private javax.swing.JTextField criterioRGB1_max_value;
    private javax.swing.JTextField criterioRGB1_min_value;
    private javax.swing.JTextField criterioRGB2_max_value;
    private javax.swing.JTextField criterioRGB2_min_value;
    private javax.swing.JTextField criterioRGB3_max_value;
    private javax.swing.JTextField criterioRGB3_min_value;
    private javax.swing.JCheckBox criterioRGB_1;
    private javax.swing.JCheckBox criterioRGB_2;
    private javax.swing.JCheckBox criterioRGB_3;
    private javax.swing.JTextField criterioYCgCr1_max_value;
    private javax.swing.JTextField criterioYCgCr1_min_value;
    private javax.swing.JTextField criterioYCgCr2_max_value;
    private javax.swing.JTextField criterioYCgCr2_min_value;
    private javax.swing.JCheckBox criterioYCgCr_1;
    private javax.swing.JCheckBox criterioYCgCr_2;
    private javax.swing.JLabel max_text;
    private javax.swing.JLabel max_text1;
    private javax.swing.JLabel min_text;
    private javax.swing.JLabel min_text1;
    private javax.swing.JLabel title;
    private javax.swing.JButton todos_button;
    // End of variables declaration//GEN-END:variables
}
