/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas.Morfologia;

import Telas.Tela_Principal_;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.awt.Point;
import Processamento.Morfologia;

/**
 *
 * @author Eloy
 */
public class ElementoEstruturante extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ElementoEstruturante.class.getName());
    private Tela_Principal_ telaPrincipal;
    private ArrayList<Point> ElemEst;
    private BufferedImage novaImagem;
    private int seletor;

    /**
     * Creates new form ElementoEstruturante
     */
    public ElementoEstruturante(Tela_Principal_ telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
        ElemEst = new ArrayList<>();
        this.seletor = 0;
        this.novaImagem = telaPrincipal.getSelectedImg();
        initComponents();
        buttonGroup1.add(eeCruz);
        buttonGroup1.add(eeBarraHor);
        buttonGroup1.add(eeBarraVer);
        buttonGroup1.add(eeQuadrado);
        buttonGroup1.add(eeRhombus);
//        buttonGroup1.setSelected(eeCruz, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        eeCruz = new javax.swing.JRadioButton();
        eeBarraHor = new javax.swing.JRadioButton();
        eeBarraVer = new javax.swing.JRadioButton();
        eeQuadrado = new javax.swing.JRadioButton();
        eeRhombus = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eeCruz.setSelected(true);
        eeCruz.setText("Cruz");
        eeCruz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeCruzActionPerformed(evt);
            }
        });

        eeBarraHor.setText("Barra horizontal");
        eeBarraHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeBarraHorActionPerformed(evt);
            }
        });

        eeBarraVer.setText("Barra vertical");
        eeBarraVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeBarraVerActionPerformed(evt);
            }
        });

        eeQuadrado.setText("Quadrado");
        eeQuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeQuadradoActionPerformed(evt);
            }
        });

        eeRhombus.setText("Rhombus");
        eeRhombus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeRhombusActionPerformed(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eeRhombus)
                    .addComponent(eeQuadrado)
                    .addComponent(eeBarraVer)
                    .addComponent(eeBarraHor)
                    .addComponent(eeCruz))
                .addContainerGap(380, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(eeCruz)
                .addGap(18, 18, 18)
                .addComponent(eeBarraHor)
                .addGap(18, 18, 18)
                .addComponent(eeBarraVer)
                .addGap(18, 18, 18)
                .addComponent(eeQuadrado)
                .addGap(18, 18, 18)
                .addComponent(eeRhombus)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eeBarraHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeBarraHorActionPerformed
        // TODO add your handling code here:
//        this.seletor =2;
    }//GEN-LAST:event_eeBarraHorActionPerformed

    private void eeRhombusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeRhombusActionPerformed
        // TODO add your handling code here:
//        this.seletor =5;
    }//GEN-LAST:event_eeRhombusActionPerformed

    private void eeCruzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeCruzActionPerformed
        // TODO add your handling code here:
//        this.seletor =1;

    }//GEN-LAST:event_eeCruzActionPerformed

    private void eeBarraVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeBarraVerActionPerformed
        // TODO add your handling code here:
//        this.seletor =3;
    }//GEN-LAST:event_eeBarraVerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

//        switch (seletor) {
//            case 1:
        if (eeCruz.isSelected()) {
            this.ElemEst.add(new Point(0, -1));
            this.ElemEst.add(new Point(0, 1));
            this.ElemEst.add(new Point(-1, 0));
            this.ElemEst.add(new Point(0, 0));
            this.ElemEst.add(new Point(1, 0));
        }
//                break;
//            case 2:
        if (eeBarraHor.isSelected()) {
            this.ElemEst.add(new Point(-1, 0));
            this.ElemEst.add(new Point(0, 0));
            this.ElemEst.add(new Point(1, 0));
        }
//                break;
//            case 3:
        if (eeBarraVer.isSelected()) {
            this.ElemEst.add(new Point(0, -1));
            this.ElemEst.add(new Point(0, 1));
            this.ElemEst.add(new Point(0, 0));
        }
//                break;
//            case 4:
        if (eeQuadrado.isSelected()) {
            this.ElemEst.add(new Point(0, -1));
            this.ElemEst.add(new Point(0, 1));
            this.ElemEst.add(new Point(0, 0));
            this.ElemEst.add(new Point(-1, 1));
            this.ElemEst.add(new Point(-1, -1));
            this.ElemEst.add(new Point(-1, 0));
            this.ElemEst.add(new Point(1, -1));
            this.ElemEst.add(new Point(1, 0));
            this.ElemEst.add(new Point(1, 1));
        }
//                break;
//            case 5:
        if (eeRhombus.isSelected()) {
            this.ElemEst.add(new Point(0, -1));
            this.ElemEst.add(new Point(0, 1));
            this.ElemEst.add(new Point(0, 0));
            this.ElemEst.add(new Point(-1, 1));
            this.ElemEst.add(new Point(-1, -1));
            this.ElemEst.add(new Point(-1, 0));
            this.ElemEst.add(new Point(1, -1));
            this.ElemEst.add(new Point(1, 0));
            this.ElemEst.add(new Point(1, 1));
            this.ElemEst.add(new Point(2, -1));
            this.ElemEst.add(new Point(2, 0));
            this.ElemEst.add(new Point(2, 1));
            this.ElemEst.add(new Point(-2, -1));
            this.ElemEst.add(new Point(-2, 0));
            this.ElemEst.add(new Point(-2, 1));
            this.ElemEst.add(new Point(1, -2));
            this.ElemEst.add(new Point(0, -2));
            this.ElemEst.add(new Point(-1, -2));
            this.ElemEst.add(new Point(1, 2));
            this.ElemEst.add(new Point(0, 2));
            this.ElemEst.add(new Point(-1, 2));
        }
//                break;
//            default:
//                break;
//        }
        this.novaImagem = Morfologia.erosaoNivelDeCinza(this.novaImagem, ElemEst);
        telaPrincipal.openInternalImg(this.novaImagem, "", "");
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void eeQuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeQuadradoActionPerformed
        // TODO add your handling code here:
//        this.seletor =4;

    }//GEN-LAST:event_eeQuadradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new ElementoEstruturante().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton eeBarraHor;
    private javax.swing.JRadioButton eeBarraVer;
    private javax.swing.JRadioButton eeCruz;
    private javax.swing.JRadioButton eeQuadrado;
    private javax.swing.JRadioButton eeRhombus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
